[package]
name = "xpu-cuda"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

description = "cuda implementation of xpu device abstraction"

[lib]
name = "xpu_cuda"
path = "src/lib.rs"

[dependencies]
xpu-core = { workspace = true }

[features]
default = []
