[build-system]
requires = ["setuptools", "wheel", "setuptools-scm", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "pysimbi"
authors = [
    {name = "Marcus DuPont"},
    {email = "md4469@nyu.edu"}
]
description = "Python module to solve hydrodynamic equations using a hip/cuda/c++ backend"
requires-python = ">=3"
keywords = ["physics", "relativity"]
license = {file = 'LICENSE'}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "Programming Language :: HIP",
    "Programming Language :: CUDA",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
]
dynamic = ["version", "readme"]
dependencies = [
    "numpy", 
    "h5py", 
    "cython", 
    "meson"
]

[project.scripts]
pysimbi = "pysimbi.__main__:main"

[options]
zip_safe = false

[tool.setuptools]
packages = ["pysimbi"]

[tool.setuptools_scm]
write_to = "pysimbi/version.py"
version_scheme = "post-release"
local_scheme = "no-local-version"

[tool.setuptools.dynamic]
readme = {file = ["README.md"]}

[project.urls]
repository    = "https://github.com/EigenDev/simbi"
documentation = "https://github.com/EigenDev/simbi"
