# =============================================================================
# gr_kerr_dragging.py
#
# the FRAME-DRAGGING manifold probe (design 44 phase C): a uniform gas on the
# ZERO-ANGULAR-MOMENTUM (S_phi = 0) manifold of a spinning kerr background,
# advected radially. on this manifold v^phi = -q v^r with q = gamma_{r phi} /
# gamma_{phi phi}, so the angular-momentum variable w = v^phi + q v^r vanishes
# identically. the RMHD flux re-reconstructs v^phi in w (not raw), so w stays
# zero to roundoff and NO spurious azimuthal momentum S_phi is generated by the
# geometric dragging profile. reconstructing v^phi raw mixes the r-dependent
# dragging into the limited slopes and grows S_phi at truncation level. a weak
# vertical seed field rides along (the CT stays div-free).
#
# gate: simbi/simulation/tests/test_kerr_grmhd.py (the w residual stays ~roundoff).
# =============================================================================

import math
from functools import partial
from typing import Annotated

from pydantic import model_validator

from simbi import ProblemParam, SimbiProblem
from simbi.types import (
    BoundaryCondition,
    CellSpacing,
    CoordSystem,
    CtMethod,
    Regime,
    Solver,
    Spacetime,
)
from simbi.types.typing import (
    GasStateGenerator,
    InitialStateType,
    StaggeredBFieldGenerator,
)


class GrKerrDragging(SimbiProblem):
    """uniform gas on the zero-angular-momentum kerr dragging manifold — the w-reconstruction probe."""

    adiabatic_index: Annotated[float, ProblemParam(4.0 / 3.0, description="adiabatic index")]
    spacetime: Annotated[Spacetime, ProblemParam(Spacetime.KERR, description="background spacetime")]
    schwarzschild_mass: Annotated[float, ProblemParam(1.0, cli=True, description="black-hole mass M")]
    kerr_spin: Annotated[float, ProblemParam(0.9, cli=True, description="dimensionless spin a")]
    inflow: Annotated[float, ProblemParam(0.15, cli=True, description="radial inflow speed |v^r|")]
    b_ref: Annotated[float, ProblemParam(1.0e-3, cli=True, description="weak seed field amplitude")]
    rho_ambient: Annotated[float, ProblemParam(1.0, description="uniform density")]
    p_ambient: Annotated[float, ProblemParam(0.1, description="uniform pressure")]

    nr: Annotated[int, ProblemParam(128, cli=True, description="radial resolution")]
    npolar: Annotated[int, ProblemParam(64, cli=True, description="polar resolution")]
    resolution: Annotated[tuple[int, int], ProblemParam((0, 0), description="computed")]
    theta_halfwidth: Annotated[float, ProblemParam(0.4, description="polar wedge half-width (rad)")]
    bounds: Annotated[
        list[tuple[float, float]],
        ProblemParam([(0.0, 0.0), (0.0, 0.0)], description="computed"),
    ]
    coord_system: Annotated[CoordSystem, ProblemParam(CoordSystem.SPHERICAL, description="coords")]
    regime: Annotated[Regime, ProblemParam(Regime.SRMHD, description="physics regime")]
    solver: Annotated[Solver, ProblemParam(Solver.HLLE, cli=True, description="solver")]
    ct_method: Annotated[CtMethod, ProblemParam(CtMethod.CONTACT, cli=True, description="CT method")]
    x1_spacing: Annotated[CellSpacing, ProblemParam(CellSpacing.LINEAR, description="radial spacing")]
    boundary_conditions: Annotated[
        list[str],
        ProblemParam(
            [
                BoundaryCondition.OUTFLOW,
                BoundaryCondition.OUTFLOW,
                BoundaryCondition.REFLECTING,
                BoundaryCondition.REFLECTING,
            ],
            description="outflow radial; reflecting theta walls",
        ),
    ]
    end_time: Annotated[float, ProblemParam(2.0, cli=True, checkpoint_safe=True, description="end time")]

    @model_validator(mode="after")
    def compute_defaults(self) -> "GrKerrDragging":
        self.resolution = (self.nr, self.npolar)
        theta_c = math.pi / 2.0
        r_plus = self.schwarzschild_mass + math.sqrt(
            max(self.schwarzschild_mass**2 - self.kerr_spin**2, 0.0)
        )
        self.bounds = [
            (max(4.0, 1.05 * r_plus), 16.0),
            (theta_c - self.theta_halfwidth, theta_c + self.theta_halfwidth),
        ]
        return self

    def q_drag(self, r: float, th: float) -> float:
        # q = gamma_{r phi}/gamma_{phi phi} for ingoing kerr-schild kerr; the ZAMO (S_phi = 0)
        # velocity is v^phi = -q v^r, so w = v^phi + q v^r = 0.
        mm, a = self.schwarzschild_mass, self.kerr_spin
        s2 = math.sin(th) ** 2
        sigma = r * r + a * a * math.cos(th) ** 2
        b = 2.0 * mm * r / sigma
        g_rphi = -a * s2 * (1.0 + b)
        g_phiphi = s2 * (sigma + a * a * s2 * (1.0 + b))
        return g_rphi / g_phiphi

    def radial_faces(self) -> list[float]:
        (rmin, rmax) = self.bounds[0]
        dr = (rmax - rmin) / self.nr
        return [rmin + ii * dr for ii in range(self.nr + 1)]

    def theta_faces(self) -> list[float]:
        (tmin, tmax) = self.bounds[1]
        dth = (tmax - tmin) / self.npolar
        return [tmin + jj * dth for jj in range(self.npolar + 1)]

    def initial_primitive_state(self) -> InitialStateType:
        nr, npolar = self.nr, self.npolar
        rf, tf = self.radial_faces(), self.theta_faces()
        r_c = [0.5 * (rf[i] + rf[i + 1]) for i in range(nr)]
        th_c = [0.5 * (tf[j] + tf[j + 1]) for j in range(npolar)]
        v_r = -abs(self.inflow)

        def gas_state() -> GasStateGenerator:
            for jj in range(npolar):
                for ii in range(nr):
                    vphi = -self.q_drag(r_c[ii], th_c[jj]) * v_r
                    yield (self.rho_ambient, v_r, 0.0, vphi, self.p_ambient)

        def b_field(bn: str) -> StaggeredBFieldGenerator:
            # a weak theta-uniform radial monopole B^r = C/r^2 (div-free on the wedge), so the CT
            # exercises a nonzero poloidal field while the gas rides the dragging manifold.
            if bn == "b1":
                r_in = self.bounds[0][0]
                for _jj in range(npolar):
                    for r in rf:
                        yield self.b_ref * r_in * r_in / (r * r)
            elif bn == "b2":
                for _jj in range(npolar + 1):
                    for _ii in range(nr):
                        yield 0.0
            else:
                for _jj in range(npolar):
                    for _ii in range(nr):
                        yield 0.0

        return (gas_state, partial(b_field, "b1"), partial(b_field, "b2"), partial(b_field, "b3"))
