[package]
name = "physics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "physics"
path = "src/lib.rs"

[dependencies]
base = { workspace = true }
containers = { workspace = true }
compute = { workspace = true }
rayon = { workspace = true }
xpu-core = { workspace = true }

[features]
default = ["hydro"]
hydro = []
mhd = []

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
xpu-host = { workspace = true }

[[bench]]
name = "euler1d"
harness = false
