[package]
name = "geometry"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "geometry"
path = "src/lib.rs"

[dependencies]
containers = { workspace = true }
utility = { workspace = true }

[dev-dependencies]
