[package]
name = "sim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "sim"
path = "src/lib.rs"

[dependencies]
compute = { workspace = true }
physics = { workspace = true }
xpu-core = { workspace = true }

[dev-dependencies]
xpu-host = { workspace = true }
