[package]
name = "compute"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "compute"
path = "src/lib.rs"

[dependencies]
base = { workspace = true }
grid = { workspace = true }
xpu-core = { workspace = true }
xpu-host = { workspace = true }
functional = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
