[package]
name = "xpu-host"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

description = "cpu host implementation of xpu device abstraction"

[lib]
name = "xpu_host"
path = "src/lib.rs"

[dependencies]
xpu-core = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]

[features]
default = []
parallel = []
