// =============================================================================
// layout.rs
//
// the three pure executor helpers the dispatch policy needs: per-axis allocation /
// execution layouts (Domain -> tuple math) + the AOT-registry lookup wrapper
// (`expect_kernel`). pure index arithmetic + `symbi_aot::kernel_by_name` — no symbi
// coupling. the other (substrate / curvilinear) layout helpers stay in `symbi`.
//
// usage:
//  let (alo, aext, vol) = alloc_layout(allocated);
//  let (grid, dlo) = exec_layout(exec);
//  let (cpu, ir) = expect_kernel::<Sc>(name);
// =============================================================================

use symbi_algebra::{Domain, OrderedNumeric};
use symbi_ir::algebra::Scalar;

// per-axis allocated lo / extent + volume — where every cell-centered buffer lives.
pub fn alloc_layout<const D: usize>(allocated: &Domain<D>) -> ([i32; D], [u32; D], usize) {
    let mut lo = [0i32; D];
    let mut ext = [0u32; D];
    for ax in 0..D {
        lo[ax] = allocated.spaces[ax].lo as i32;
        ext[ax] = allocated.spaces[ax].size() as u32;
    }
    (lo, ext, allocated.volume())
}

// per-axis grid size / domain lo for a kernel launch's execution window.
pub fn exec_layout<const D: usize>(dom: &Domain<D>) -> ([u32; D], [i32; D]) {
    let mut grid = [0u32; D];
    let mut dlo = [0i32; D];
    for ax in 0..D {
        grid[ax] = dom.spaces[ax].size() as u32;
        dlo[ax] = dom.spaces[ax].lo as i32;
    }
    (grid, dlo)
}

/// resolve an AOT kernel by name, or panic with an ACTIONABLE message. a missing kernel almost
/// always means it was not EMITTED in `symbi-aot/build.rs` for the requested combination — an
/// unsupported (regime, dimension D, geometry / cyl-plane, Riemann solver) tuple, or a dispatch-
/// name typo — NOT a runtime bug. the bare `kernel_by_name(..).unwrap()` would just say "missing
/// <name>"; this points a new user at WHERE to look. use it for every substrate kernel lookup.
pub fn expect_kernel<S: Scalar + OrderedNumeric>(
    name: &str,
) -> (symbi_aot::KernelFn<S>, &'static str) {
    symbi_aot::kernel_by_name::<S>(name).unwrap_or_else(|| {
        panic!(
            "no AOT kernel '{name}' was emitted for this configuration. it is generated by \
             symbi-aot/build.rs per (regime, dimension D, geometry / cyl-plane, Riemann solver) — \
             a missing kernel means an unsupported combination (e.g., a D / solver / cyl-plane the \
             family does not cover) or a dispatch-name mismatch. check the build.rs emission for \
             this regime + the dispatch name above."
        )
    })
}
