// =============================================================================
// build.rs
//
// the build-time codegen step (docs/design/10 §4, P2.2/P2.3). runs the substrate
// to lower conservation laws to stencil IR graphs, then for each one: emits a
// compilable Rust `pub fn` via `emit_kernel_cpu` AND serializes the backend-neutral
// lowered IR (Prepared) per kernel (docs/design/15 §3) to a `{kernel_name}.ir.json`
// blob, all written to OUT_DIR. the crate's lib.rs `include!`s the CPU fns and
// exposes the IR blobs as consts; downstream crates (tests here; `symbi`'s
// SubstrateKernelSet) call them — the IR blob renders to any backend at runtime
// via `render_from_ir`.
//
// generates two kernels:
//   - godunov_mass_1d        — single mass law, separate output buffer (P2.2).
//   - iso_godunov_euler_1d   — isothermal Euler (mass + x-momentum), IN-PLACE
//                              conserved update (P2.3), matching the production
//                              iso godunov for the no-gravity case.
//
// in production (a later refactor) this codegen runs from a RegimeSpec registry;
// here it generates a fixed set to prove the mechanism.
// =============================================================================

use std::fs;
use std::path::Path;
use std::sync::Mutex;

// collects (cpu_include_file, kernel_name) for every kernel emitted this run, so
// main() writes ONE registry module (docs/design/15 §3) instead of this crate
// hand-maintaining include!/const lines. populated by write_both — the single
// emission chokepoint (write_kernel is only ever called through it). build.rs is
// single-threaded; the Mutex is just to satisfy `static` mutability.
static REGISTRY: Mutex<Vec<(String, String)>> = Mutex::new(Vec::new());

// every kernel's CONSTRUCTION lives in symbi-discretize as a builder (iso_c2p,
// hlle_flux, srhd_hlle_flux, godunov_euler/snapshot/rk2, ...). build.rs only
// drives them: build the graph via a builder, then emit (CPU Rust + CUDA source).
use symbi_discretize::{
    body_feedback_gv, body_feedback_iso_gv, body_source_gv, body_source_iso_gv,
    geometric_momentum_source_probe_gv, geometry_probe_gv, godunov_mass_gv,
    inertial_momentum_probe_gv, iso_ghost_fill_gv, iso_wave_speed_map_gv,
    nmhd_wave_speed_map_gv,
    rmhd_average_efield_gv, rmhd_bcell_from_bface_gv, rmhd_bcell_godunov_euler_gv,
    rmhd_bcell_godunov_rk2_gv, rmhd_ct_curl_2d_dir_gv, rmhd_ct_curl_3d_dir_gv,
    rmhd_ct_curl_cyl_rz_gv, rmhd_ct_curl_cyl_rphi_gv, rmhd_edge_emf_gv,
    rmhd_ghost_fill_gv, rmhd_save_efield_gv, rmhd_wave_speed_map_gv, rmhd_wave_speeds_cell_gv,
    snapshot_gv, srhd_wave_speed_map_gv, Coords, GeoSource, Spacing,
};
use symbi_discretize::GvKernel;
use symbi_ir::emit::{Precision, Target, TargetConfig};
use symbi_ir::graph::{Graph, NodeId};
use symbi_ir::gv::{try_fuse, LaunchGrade};
use symbi_ir::{emit_kernel_cpu, emit_kernel_cpu_serial, prepare, prepared_to_ir, FieldBind, KernelEmitInputs};

// the immersed-body kernels pack one slot per body; the count is owned by the
// runtime (symbi-ib) and imported here so codegen and runtime share one definition.
use symbi_ib::collection::MAX_BODIES;

fn write_kernel(out_dir: &str, file: &str, desc: &symbi_ir::emit::KernelDescriptor) {
    let buffers: Vec<(String, bool)> = desc
        .field_bindings
        .iter()
        .map(|b| (b.field.name(), b.is_output))
        .collect();
    // the signature order is recorded in the generated file's header so callers
    // (and a human) can match the positional kernel signature.
    let mut src = String::new();
    src.push_str("// generated by build.rs from a substrate RegimeSpec — do not edit.\n");
    src.push_str(&format!("// buffers (in signature order): {:?}\n", buffers));
    src.push_str(&format!("// scalars (in signature order): {:?}\n", desc.param_names));
    src.push_str(&desc.source);
    fs::write(Path::new(out_dir).join(file), src).expect("failed to write generated kernel");
}

// emit from one IR graph: the CPU Rust (compiled into the crate) AND the
// backend-neutral lowered IR — `prepare` (scalarize + buffer-bind, no renderer)
// serialized to `{kernel_name}.ir.json` and exposed as a const, rendered to any
// backend at runtime via `render_from_ir` (docs/design/15 §3). one physics graph,
// one neutral artifact. `prepare` runs twice (once inside emit_kernel_cpu, once
// here) — deterministic, build-time only.
//
// the CPU file name is DERIVED from kernel_name (`{kernel_name}_generated.rs`), which
// is unique per (regime, ndim, dir), so the SAME regime can be instantiated at
// multiple ndims without colliding on a fixed filename (D-generic ports).
// serial-twin generation is ON by default (the universal cover executor's per-block
// kernel). opt out with SYMBI_GEN_SERIAL=0/off/false/no for a ~1.5x-leaner build.
fn serial_twins_enabled() -> bool {
    // debug-emit-knobs gates the SYMBI_GEN_SERIAL read (build scripts test CARGO_FEATURE_*, not cfg!); feature off (default) = canonical env-unset shape (true, serial twins on).
    if std::env::var_os("CARGO_FEATURE_DEBUG_EMIT_KNOBS").is_none() {
        return true;
    }
    match std::env::var("SYMBI_GEN_SERIAL") {
        Ok(s) => !matches!(s.trim().to_ascii_lowercase().as_str(), "0" | "off" | "false" | "no"),
        Err(_) => true,
    }
}

fn write_both(out_dir: &str, graph: &Graph, inputs: &KernelEmitInputs) {
    let cpu_file = format!("{}_generated.rs", inputs.kernel_name);
    write_kernel(out_dir, &cpu_file, &emit_kernel_cpu(graph, inputs));
    let prepared = prepare(graph, inputs);
    let ir = prepared_to_ir(&prepared);
    fs::write(Path::new(out_dir).join(format!("{}.ir.json", inputs.kernel_name)), &ir)
        .expect("failed to write neutral ir blob");
    REGISTRY
        .lock()
        .unwrap()
        .push((cpu_file, inputs.kernel_name.to_string()));

    // emit a `{name}_serial` twin (no internal rayon) so the cover executor can
    // dispatch a disjoint block cover in ONE fork-join — the universal scheduling
    // path. ON by default (the +13% auto-block win is the standard behavior); opt
    // out with SYMBI_GEN_SERIAL=0/off/false for a leaner/faster build (the executor
    // then falls back to the parallel kernel — same results, no auto-blocking).
    if serial_twins_enabled() {
        let serial_name = format!("{}_serial", inputs.kernel_name);
        let serial_inputs = KernelEmitInputs {
            kernel_name:      &serial_name,
            ndim:             inputs.ndim,
            target:           inputs.target.clone(),
            field_inputs:     inputs.field_inputs,
            scalar_params:    inputs.scalar_params,
            field_writes:     inputs.field_writes,
            coord_components: inputs.coord_components,
            device_preamble:  inputs.device_preamble,
            tile_spec:        inputs.tile_spec,
        };
        let serial_file = format!("{serial_name}_generated.rs");
        write_kernel(out_dir, &serial_file, &emit_kernel_cpu_serial(graph, &serial_inputs));
        // the neutral IR blob is renderer-agnostic (same graph) — reuse it under
        // the serial name so the registry stays uniform (CPU-only path; unused).
        fs::write(Path::new(out_dir).join(format!("{serial_name}.ir.json")), &ir)
            .expect("failed to write serial ir blob");
        REGISTRY.lock().unwrap().push((serial_file, serial_name));
    }
}

// write the single registry module from everything write_both emitted this run:
// one `include!` per CPU kernel + one `<KERNEL>_IR` blob const per kernel (the
// serialized backend-neutral lowered IR / Prepared, docs/design/15 §3). the const
// name + .ir.json filename derive uniformly from kernel_name (iso_c2p_1d ->
// ISO_C2P_1D_IR + iso_c2p_1d.ir.json), so no per-kernel hand-registration survives.
fn write_registry(out_dir: &str) {
    let reg = REGISTRY.lock().unwrap();
    let mut src = String::new();
    src.push_str("// generated by build.rs (docs/design/15 §3) — the kernel registry.\n");
    src.push_str("// one include! per CPU kernel + one neutral IR blob const per kernel. do not edit.\n");
    for (cpu_file, kernel_name) in reg.iter() {
        src.push_str(&format!(
            "include!(concat!(env!(\"OUT_DIR\"), \"/{cpu_file}\"));\n"
        ));
        src.push_str(&format!(
            "pub const {}_IR: &str = include_str!(concat!(env!(\"OUT_DIR\"), \"/{kernel_name}.ir.json\"));\n",
            kernel_name.to_uppercase(),
        ));
    }
    // the name -> (structured CPU fn, neutral IR blob) lookup (docs/design/15 §5):
    // the D-generic SubstrateKernelSet<.., const D> builds a kernel name from
    // (regime, ndim, dir) and resolves the instance HERE — no hand-maintained
    // `match (D, dir)` per regime. `KernelFn<S>` (lib.rs) is the structured ABI fn
    // pointer; the generic fn item `k::<S>` coerces to it. one entry per kernel,
    // auto-registered from everything emitted this run.
    src.push_str("\n/// resolve a generated kernel by name to its structured CPU fn + neutral IR blob.\n");
    src.push_str("pub fn kernel_by_name<S: Scalar + OrderedNumeric>(name: &str) -> Option<(KernelFn<S>, &'static str)> {\n");
    src.push_str("    Some(match name {\n");
    for (_cpu_file, kernel_name) in reg.iter() {
        src.push_str(&format!(
            "        \"{kernel_name}\" => ({kernel_name}::<S>, {}_IR),\n",
            kernel_name.to_uppercase(),
        ));
    }
    src.push_str("        _ => return None,\n    })\n}\n");
    fs::write(Path::new(out_dir).join("kernels_registry.rs"), src)
        .expect("failed to write kernel registry");
}

// the single-scalar lattice-map ghost fill — the staggered bface transverse-halo
// fill dispatches it per component (any cell- or face-anchored scalar works; the
// buffer resolves coords against its own staggered lo).
fn gen_scalar_ghost_fill(out_dir: &str) {
    let (k, writes) = symbi_discretize::scalar_ghost_fill_gv(3);
    emit_gv(out_dir, "scalar_ghost_fill_3d", 3, &k, &writes);
}

// amr transfer kernels (gv_refinement.rs builders): one restrict + three prolong
// orders per dimension, refinement ratio 2. field-agnostic single scalar
// src/dst, dispatched per component via dispatch_fields_each.
fn gen_refine_transfer(out_dir: &str, ndim: u8) {
    use symbi_discretize::{
        refine_acc_face_gv, refine_prolong_gv, refine_restrict_face_gv, refine_restrict_gv,
        field_axpy_shift_gv, field_copy_gv, field_fill_gv, ProlongOrder,
    };
    // names via `KernelId` — the SAME source the dispatch reads, so the registry
    // key and the lookup key cannot drift.
    use symbi_ir::{KernelId, ProlongTag};
    let nd = ndim as usize;
    let (k, writes) = refine_restrict_gv(nd, 2);
    emit_gv(out_dir, KernelId::RefineRestrict { ndim }.name(), ndim, &k, &writes);
    // register / snapshot utilities (the amr gpu pass).
    let (k, writes) = field_copy_gv(nd);
    emit_gv(out_dir, KernelId::FieldCopy { ndim }.name(), ndim, &k, &writes);
    let (k, writes) = field_fill_gv(nd);
    emit_gv(out_dir, KernelId::FieldFill { ndim }.name(), ndim, &k, &writes);
    let (k, writes) = field_axpy_shift_gv(nd);
    emit_gv(out_dir, KernelId::FieldAxpyShift { ndim }.name(), ndim, &k, &writes);
    // staggered face restriction + prolongation (mhd bface) + the accumulating
    // child sum (fine flux register): one instance per face-normal axis.
    for ax in 0..ndim {
        let axu = ax as usize;
        let (k, writes) = refine_restrict_face_gv(nd, 2, axu);
        emit_gv(out_dir, KernelId::RefineRestrictFace { axis: ax, ndim }.name(), ndim, &k, &writes);
        let (k, writes) = symbi_discretize::refine_prolong_face_gv(nd, 2, axu);
        emit_gv(out_dir, KernelId::RefineProlongFace { axis: ax, ndim }.name(), ndim, &k, &writes);
        let (k, writes) = refine_acc_face_gv(nd, 2, axu);
        emit_gv(out_dir, KernelId::RefineAccFace { axis: ax, ndim }.name(), ndim, &k, &writes);
        let (k, writes) = symbi_discretize::refine_acc_edge_gv(nd, 2, axu);
        emit_gv(out_dir, KernelId::RefineAccEdge { axis: ax, ndim }.name(), ndim, &k, &writes);
    }
    for (tag, order) in [
        (ProlongTag::Pcm, ProlongOrder::Pcm),
        (ProlongTag::Plm, ProlongOrder::Plm),
        (ProlongTag::Ppm, ProlongOrder::Ppm),
    ] {
        let (k, writes) = refine_prolong_gv(nd, 2, order);
        emit_gv(out_dir, KernelId::RefineProlong { order: tag, ndim }.name(), ndim, &k, &writes);
        // multi-field (prim batch) prolong: 3D hot path only, ncomp 4 (isothermal)
        // and 5 (adiabatic/srhd) — one launch over the whole prim set.
        if ndim == 3 {
            for ncomp in [4u8, 5u8] {
                let (k, writes) =
                    symbi_discretize::refine_prolong_multi_gv(nd, 2, order, ncomp as usize);
                emit_gv(
                    out_dir,
                    KernelId::RefineProlongMulti { order: tag, ncomp, ndim }.name(),
                    ndim, &k, &writes,
                );
            }
        }
    }
}

// P2.2: single mass law, writing to a SEPARATE output buffer — the gv divergence + update.
fn gen_godunov_mass_1d(out_dir: &str) {
    let g = Geom::cart(1);
    let (k, writes) = godunov_mass_gv(g.coords, &g.spacing, &g.axes, 1);
    emit_gv(out_dir, "godunov_mass_1d", 1, &k, &writes);
}

// P2.3 (corrected): isothermal Euler godunov, IN-PLACE conserved update,
// DIMENSION-GENERIC. mass + one scalar law PER momentum component, looped over
// `ndim` — each momentum component's flux is a vector whose divergence sums over
// the sweep axes (`finite_volume_scheme` lowers that D-generically). there is NO
// per-dimension scalar-momentum shortcut (the func_nd anti-pattern the original
// `iso_godunov_euler_1d` fell into); codegen instantiates this one builder per
// ndim, the dimension is only a generated kernel-instance name.
// the kernel-name suffix for a coordinate system (matches the runtime `coord_suffix` in
// regimes/substrate_kernels.rs): Cartesian is unsuffixed, spherical/cylindrical get
// `_sph`/`_cyl` (the area-weighted divergence + geometric source + per-cell CFL widths).
fn coords_suffix(coords: Coords) -> &'static str {
    match coords {
        Coords::Cartesian => "",
        Coords::Spherical => "_sph",
        Coords::Cylindrical => "_cyl",
    }
}

// =============================================================================
// **B6-iv (4c-restructure) — DATA-DRIVEN AOT BAKE MATRIX**.
//
// `RegimeBuild` + `FamilyKind` declare every point in the fused-kernel bake
// matrix as DATA, not as copy-paste calls. the codegen loop in main() walks
// these tables × ndim and dispatches to the one `gen_godunov_euler_unified`
// chokepoint. adding a regime or a family is a row addition; adding a
// geometry is a column. zero copy-paste. SRHD/RMHD + curvilinear extensions
// follow once their fused-source builders validate against the GPU.
// =============================================================================

/// one row in the regime bake table — the kernel-name prefix + whether the
/// regime carries an energy conservation law. iso (mass + mom only) sets
/// `has_energy = false`; adiabatic / SRHD / RMHD set `true`.
struct RegimeBuild {
    prefix:     &'static str,
    has_energy: bool,
}

/// every regime we AOT-bake fused-source kernels for. SRHD + RMHD slot in
/// as additional rows once their fused-source path validates on the GPU.
const REGIMES: &[RegimeBuild] = &[
    RegimeBuild { prefix: "iso",       has_energy: false },
    RegimeBuild { prefix: "adiabatic", has_energy: true  },
];

/// build-time identity of a fused-source family — one variant per AOT slug.
/// mirrors the runtime `symbi_hydro::FusedSourceFamily` but carries NO
/// runtime params: `source_specs(d, has_energy)` materializes the spec list
/// build.rs needs from the symbi-hydro factory functions, parameterized by
/// ndim + the regime's energy flag.
#[derive(Clone, Copy)]
enum FamilyKind {
    UniformAccel,
    PointMassGrav,
}

impl FamilyKind {
    fn slug(self) -> &'static str {
        match self {
            Self::UniformAccel  => "uniform_accel",
            Self::PointMassGrav => "point_mass_grav",
        }
    }

    fn source_specs(self, d: usize, has_energy: bool) -> Vec<symbi_hydro::source_spec::SourceSpec> {
        match self {
            Self::UniformAccel => {
                symbi_hydro::source_spec::uniform_acceleration_sources(d, has_energy)
            }
            Self::PointMassGrav => {
                symbi_hydro::source_spec::point_mass_gravity_sources(d, has_energy)
            }
        }
    }
}

/// every fused-source family we AOT-bake. adding a family (accretion sink,
/// immersed-body gravity, ...) is one row here once the corresponding
/// `*_sources` factory + `FusedSourceFamily` variant exist.
const FUSED_FAMILIES: &[FamilyKind] = &[
    FamilyKind::UniformAccel,
    FamilyKind::PointMassGrav,
];

// a kernel instance's discretization config — the three facts that travel together per
// instance (docs/design/18): the coordinate system, the vector-component count `ncomp`
// (the momentum/velocity DOF), and the grid-axis -> coordinate-role map `axes`. cartesian
// and spherical use the identity axes + ncomp = ndim (the grid axes ARE the coordinates);
// cylindrical r-z AXISYMMETRIC decouples them — a 2-axis (r,z) grid carrying a 3-component
// velocity (v_r, v_phi, v_z), phi folded as a symmetry coordinate that carries the swirl.
#[derive(Clone)]
struct Geom {
    coords:  Coords,
    ncomp:   u8,
    axes:    Vec<usize>,
    // per-grid-axis spacing (len == naxes == ndim). defaults to all-uniform;
    // override with `with_spacing` for the log-radial spherical instances.
    spacing: Vec<Spacing>,
}

impl Geom {
    // the common shape: identity-or-decoupled axes with all-uniform spacing.
    fn make(coords: Coords, ncomp: u8, axes: Vec<usize>) -> Self {
        let spacing = vec![Spacing::Uniform; axes.len()];
        Self { coords, ncomp, axes, spacing }
    }
    fn cart(ndim: u8) -> Self {
        Self::make(Coords::Cartesian, ndim, (0..ndim as usize).collect())
    }
    fn sph(ndim: u8) -> Self {
        Self::make(Coords::Spherical, ndim, (0..ndim as usize).collect())
    }
    // identity-axis instance at an arbitrary coordinate system (ncomp == ndim, the
    // grid axes ARE the coordinates) — the body-source / geometry-probe shape.
    fn identity(coords: Coords, ndim: u8) -> Self {
        Self::make(coords, ndim, (0..ndim as usize).collect())
    }
    // cylindrical r-z axisymmetric: 2-axis grid (r,z) -> coords [0,2], 3-component velocity
    // (the swirl v_phi is carried as the out-of-plane DOF). ncomp > naxes -> "_cyl_rz".
    fn cyl_rz() -> Self {
        Self::make(Coords::Cylindrical, 3, vec![0, 2])
    }
    // cylindrical r-phi disk: 2-axis grid (r,phi) -> coords [0,1], 2-component velocity
    // (the natural cylindrical 2D plane). ncomp == naxes -> "_cyl".
    fn cyl_rphi() -> Self {
        Self::make(Coords::Cylindrical, 2, vec![0, 1])
    }
    // cylindrical r-phi DISK MHD: 2-axis grid (r,phi) -> coords [0,1], 3-component B/velocity
    // (the out-of-plane vertical B_z / v_z is the lifted DOF). ncomp > naxes BUT axes=[0,1]
    // -> "_cyl_rphi" (distinct from r-z [0,2]; both are DOF=3 so the suffix keys on the axes).
    fn cyl_rphi_mhd() -> Self {
        Self::make(Coords::Cylindrical, 3, vec![0, 1])
    }
    // cylindrical 1D radial: r only (coords [0]), 1-component velocity. the radial
    // hoop-pressure source + area ~ r divergence. ncomp == naxes -> "_cyl".
    fn cyl_1d() -> Self {
        Self::make(Coords::Cylindrical, 1, vec![0])
    }
    // cylindrical 3D (r,phi,z): full natural plane, coords [0,1,2], 3-component velocity.
    // ncomp == naxes -> "_cyl" (NDIM=3 disambiguates from the 2D _cyl in the name).
    fn cyl_3d() -> Self {
        Self::make(Coords::Cylindrical, 3, vec![0, 1, 2])
    }
    // override the default all-uniform spacing (e.g. a log-radial spherical grid).
    fn with_spacing(mut self, spacing: Vec<Spacing>) -> Self {
        self.spacing = spacing;
        self
    }
    // the cylindrical 2D plane is keyed on the AXIS SET (matching the runtime mhd_geom_suffix):
    // r-z axisymmetric [0,2] -> "_cyl_rz" (out-of-plane phi); r-phi disk MHD [0,1] with the DOF
    // lift (ncomp>naxes) -> "_cyl_rphi" (out-of-plane z). the natural hydro disk [0,1] DOF==naxes
    // and 1D/3D stay "_cyl" (DOF==ndim, matching the hydro geom_suffix). both 2D MHD planes are
    // DOF=3, so ncomp-vs-naxes alone can't tell them apart — the axes do.
    fn suffix(&self) -> &'static str {
        match self.coords {
            Coords::Cartesian => "",
            Coords::Spherical => "_sph",
            Coords::Cylindrical => match self.axes.as_slice() {
                [0, 2] => "_cyl_rz",
                [0, 1] if self.ncomp as usize > self.axes.len() => "_cyl_rphi",
                _ => "_cyl",
            },
        }
    }
}

// every gen_* emits a GV-traced kernel through `emit_gv` — Gv is the sole IR front end; the
// legacy DiscretizeCtx / Expr DSL path is gone.

// the emit chokepoint for a GV-TRACED kernel (symbi-hydro physics instantiated at S=Gv): the
// `GvKernel` already carries the graph + the ABI manifest (field inputs, scalar params, coord
// axes), so the gen just asserts the graph is clean and write_both's it with the recorded
// manifest.
fn emit_gv(out_dir: &str, kernel_name: &str, ndim: u8, k: &GvKernel, writes: &[(String, FieldBind, NodeId)]) {
    assert!(!k.graph.has_errors(), "{kernel_name} (gv) graph errors: {:?}", k.graph.errors());
    // docs/design/22 Gate 3: the smem tile intent (per-axis SLAB declared by the
    // builder via with_tile_spec) is OPT-IN behind SYMBI_GPU_SMEM, so the default
    // build stays byte-identical (flat) until the GPU smem path is hardware-validated.
    // the `rerun-if-env-changed` in `main` keeps the A/B honest — without it cargo
    // would silently reuse a cached build and invalidate a smem-on-vs-off comparison.
    let tile_spec = if std::env::var_os("SYMBI_GPU_SMEM").is_some() {
        k.infer_tile_spec()
    } else {
        None
    };
    write_both(out_dir, &k.graph, &KernelEmitInputs {
        kernel_name,
        ndim,
        target:           TargetConfig { target: Target::Cuda, precision: Precision::F64 },
        field_inputs:     &k.field_inputs,
        scalar_params:    &k.scalar_params,
        field_writes:     writes,
        coord_components: &k.coord_components,
        device_preamble:  &[],
        tile_spec: tile_spec.as_ref(),
    });
}

// the curvilinear geometric momentum source the godunov binds, by regime prefix: RMHD's
// magnetic-tension-aware source via prim+bcell, else the hydro pressure+inertial source
// via cons.mom (no-op for Cartesian).
fn geo_source(prefix: &str) -> GeoSource {
    match prefix {
        "rmhd" => GeoSource::Rmhd,
        "nmhd" => GeoSource::NewtonianMhd,
        "imhd" => GeoSource::IsothermalMhd,
        _ => GeoSource::Hydro { inertial: matches!(prefix, "iso" | "adiabatic" | "srhd") },
    }
}

// the SINGLE godunov emit chokepoint for BOTH fused / unfused variants. the
// integrator stage is no longer a codegen axis: one `{prefix}_godunov_stage{geom_suffix}_{D}d`
// kernel takes the SSP Shu-Osher convex coefficients `(a0, ac)` as RUNTIME scalars, so the
// same kernel serves forward-Euler, SSP-RK2, and SSP-RK3 (the driver feeds the per-stage
// coefficients). `fused = None` emits the plain kernel; `fused = Some((slug, specs))` adds
// the `_with_{slug}` infix and splices the specs into the forward-Euler operator. one helper
// covers the cross-product — (fused × regime × ndim × geometry) is data, never copy-paste.
fn gen_godunov_stage(
    out_dir: &str,
    ndim: u8,
    prefix: &str,
    has_energy: bool,
    geom: Geom,
    fused: Option<(&str, &[&symbi_hydro::source_spec::SourceSpec])>,
) {
    let suffix_with = fused.map(|(slug, _)| format!("_with_{slug}")).unwrap_or_default();
    let name = format!("{prefix}_godunov_stage{suffix_with}{}_{ndim}d", geom.suffix());
    let no_sources: [&symbi_hydro::source_spec::SourceSpec; 0] = [];
    let sources: &[&symbi_hydro::source_spec::SourceSpec] = match fused {
        Some((_, s)) => s,
        None         => &no_sources,
    };
    let (k, writes) = symbi_discretize::gv::godunov_stage_gv_with_fused_sources(
        geom.coords, &geom.spacing, &geom.axes, ndim, geom.ncomp as usize, has_energy,
        geo_source(prefix), sources, /* mag_from_bcell = */ false, // unfused: geo source reads prim.mag
    );
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the IMMERSED-BODY source fused into the godunov stage (frame-correct: Cartesian
// physics projected onto the physical basis). its own bake — the body source is a
// set of coord-dependent `BuiltSource`s (`body_source_built`), not a coord-agnostic
// `SourceSpec` family, so it doesn't ride the FUSED_FAMILIES loop. one launch:
// `cons_new = godunov(cons) + ac*dt*(gravity + accretion)` for MAX_BODIES bodies.
fn gen_godunov_with_body_source(out_dir: &str, ndim: u8, prefix: &str, has_energy: bool, geom: Geom) {
    let name = format!("{prefix}_godunov_stage_with_body_source{}_{ndim}d", geom.suffix());
    let built = symbi_discretize::body_source_built(
        geom.coords, ndim as usize, geom.ncomp as usize, &geom.axes, MAX_BODIES, has_energy,
    );
    let refs: Vec<(&str, &symbi_hydro::source_spec::BuiltSource)> =
        built.iter().map(|(t, b)| (t.as_str(), b)).collect();
    let (k, writes) = symbi_discretize::gv::godunov_stage_gv_with_fused_built(
        geom.coords, &geom.spacing, &geom.axes, ndim, geom.ncomp as usize, has_energy,
        geo_source(prefix), &refs, /* mag_from_bcell = */ false,
    );
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the STANDALONE ADDITIVE source kernel `{prefix}_source_with_{slug}{geom}_{D}d`: `cons += dt*S`
// for the spec family, as a separate per-stage pass (the general source executor). same splice as
// the fused godunov, minus the flux/combine — so plain godunov + this pass is the
// proven-equivalent decomposition of the fused stage. the driver passes dt = ac*dt.
fn gen_source_apply(
    out_dir: &str,
    ndim: u8,
    prefix: &str,
    has_energy: bool,
    geom: Geom,
    slug: &str,
    sources: &[&symbi_hydro::source_spec::SourceSpec],
) {
    let name = format!("{prefix}_source_with_{slug}{}_{ndim}d", geom.suffix());
    let (k, writes) = symbi_discretize::gv::source_apply_gv(
        geom.coords, &geom.spacing, &geom.axes, ndim, geom.ncomp as usize, has_energy, sources,
    );
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// P3.3: the isothermal face FLUX — reconstruction composed with the one
// canonical HLLE (symbi_discretize::iso_hlle_flux). dimension-generic: it loops
// the momentum components internally; codegen instantiates one kernel per (ndim,
// sweep dir) — the reconstruction axis `dir` is baked into the kernel instance.
fn gen_iso_face_flux(out_dir: &str, ndim: u8, dir: u8) {
    let name = format!("iso_face_flux_{ndim}d_{dir}");
    // the gv single-source physics: PLM reconstruction (Gv stencil) composed with
    // symbi-hydro's `riemann::hlle` at the `IsoNewtonian` regime — the PURE iso (constant
    // cs, p=cs^2*rho recomputed from rho, NO reconstructed prim.pre, no energy flux),
    // replacing the `iso_hlle_flux` Expr builder. cartesian-only + ncomp == ndim.
    let (k, writes) = match ndim {
        1 => symbi_discretize::gv::iso_flux_gv::<1>(dir),
        2 => symbi_discretize::gv::iso_flux_gv::<2>(dir),
        3 => symbi_discretize::gv::iso_flux_gv::<3>(dir),
        _ => panic!("iso_flux_gv: unsupported ndim {ndim}"),
    };
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the adiabatic face flux: hlle_flux with the energy component (mass + momentum +
// energy). same EOS-generic body as the iso flux, plus E = p/(gamma-1)+0.5*rho|v|^2
// and F_E = (E+p)*vn.
fn gen_adiabatic_face_flux(out_dir: &str, ndim: u8, dir: u8, geom: Geom) {
    let name = format!("adiabatic_face_flux{}_{ndim}d_{dir}", geom.suffix());
    // the CARTESIAN adiabatic face flux is the gv single-source physics: PLM reconstruction
    // (a Gv stencil via field_shifted) composed with symbi-hydro's `riemann::hlle` at S=Gv
    // (adiabatic_flux_gv) — replacing the hand-written hlle_flux Expr builder + its
    // per-component U/F. ncomp == ndim == D, sweep coordinate == grid axis `dir`. cyl r-z
    // (ncomp != ndim, non-identity axes) stays on the Expr builder below until the gv flux
    // generalizes over ncomp + the axes mapping (the c2p pattern). numerically equiv (ULP).
    let (k, writes) = if geom.coords == Coords::Cartesian {
        match ndim {
            1 => symbi_discretize::gv::adiabatic_flux_gv::<1>(dir),
            2 => symbi_discretize::gv::adiabatic_flux_gv::<2>(dir),
            3 => symbi_discretize::gv::adiabatic_flux_gv::<3>(dir),
            _ => panic!("adiabatic_flux_gv: unsupported ndim {ndim}"),
        }
    } else {
        // cyl r-z (ncomp=3 swirl on the 2D (r,z) grid): the sweep coordinate is axes[dir].
        assert!(geom.ncomp == 3 && ndim == 2, "non-cartesian adiabatic flux is only cyl r-z");
        symbi_discretize::gv::adiabatic_flux_cyl_rz_gv(dir)
    };
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// P4: isothermal cons->prim (prim.rho = cons.den; prim.vel = cons.mom/cons.den).
// pointwise, dimension-generic.
fn gen_iso_c2p(out_dir: &str, ndim: u8) {
    let name = format!("iso_c2p_{ndim}d");
    // built from symbi-hydro's `IsoNewtonian::to_primitive` + the `Isothermal::pressure`
    // closure at S=Gv — the SINGLE-SOURCE physics — not a hand-written Expr builder (gv
    // migration). iso c2p is geometry-independent and ncomp == ndim (the cyl r-z swirl
    // has no iso c2p), so this is the ONLY iso c2p path: no geom branch, no retained
    // builder. node structure is bit-identical to the old `iso_c2p` builder.
    let (k, writes) = match ndim {
        1 => symbi_discretize::gv::iso_c2p_gv::<1>(),
        2 => symbi_discretize::gv::iso_c2p_gv::<2>(),
        3 => symbi_discretize::gv::iso_c2p_gv::<3>(),
        _ => panic!("iso_c2p_gv: unsupported ndim {ndim}"),
    };
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// P4: isothermal CFL wave-speed map (per-cell lambda); the host reduces by max. for
// curvilinear coords it folds per-cell PHYSICAL widths (cell_inv_phys_widths) instead of
// a uniform inv_dx; the iso map is shared by the adiabatic/Newton CFL too.
fn gen_iso_wave_speed_map(out_dir: &str, ndim: u8, geom: Geom) {
    let name = format!("iso_wave_speed_map{}_{ndim}d", geom.suffix());
    let (k, writes) =
        iso_wave_speed_map_gv(geom.coords, &geom.spacing, &geom.axes, ndim as usize);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// finish the iso KernelSet: snapshot (cons -> u_n copy) and the RK2 update.

// snapshot: u_n = cons (a pure pointwise copy), dimension-generic. with
// has_energy it also copies cons.nrg.
fn gen_snapshot(out_dir: &str, ndim: u8, prefix: &str, has_energy: bool, geom: Geom) {
    let name = format!("{prefix}_snapshot{}_{ndim}d", geom.suffix());
    // snapshot is a pure copy — geometry-independent, gv for EVERY coord system.
    let (k, writes) = snapshot_gv(geom.ncomp as usize, has_energy);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the GEOMETRY-DEPENDENT hydro kernels for ALL THREE EOS regimes (iso / adiabatic /
// srhd) at one (ndim, Geom): the one godunov-stage kernel (area-weighted divergence +
// the regime-shared `GeoSource::Hydro` geometric source — pressure hoop + inertial
// centrifugal/coriolis, all falling out of the Geom) + the CFL wave-speed maps (iso
// shared by iso+adiabatic; srhd its own). these are the ONLY curvilinear-specific
// kernels for a DOF == NDIM coordinate system — the c2p / flux / snapshot / ghost are
// pointwise / geometry-independent at ncomp == NDIM, so the runtime reuses the
// cartesian instances. ONE helper drives every (spherical, cylindrical-natural) cell.
fn gen_curvilinear_hydro(out_dir: &str, ndim: u8, geom: Geom) {
    gen_godunov_stage(out_dir, ndim, "adiabatic", true, geom.clone(), None);
    gen_godunov_stage(out_dir, ndim, "iso", false, geom.clone(), None);
    gen_iso_wave_speed_map(out_dir, ndim, geom.clone());
    gen_godunov_stage(out_dir, ndim, "srhd", true, geom.clone(), None);
    gen_srhd_wave_speed_map(out_dir, ndim, geom);
}

// the adiabatic (ideal-gas) cons->prim: p = (gamma-1)*(nrg - 0.5*rho*|v|^2),
// closed form. pointwise, dimension-generic. one more EOS closure under the same
// flux/cfl as the isothermal one (#2 of the iso/adiabatic split).
fn gen_adiabatic_c2p(out_dir: &str, ndim: u8, geom: Geom) {
    let name = format!("adiabatic_c2p{}_{ndim}d", geom.suffix());
    // built from symbi-hydro's `Cons::to_primitive` at S=Gv — the SINGLE-SOURCE physics
    // (gv migration). c2p is POINTWISE + geometry-independent: only the velocity-component
    // count `ncomp` varies (cartesian/spherical: ncomp == ndim; cyl r-z: ncomp = 3, the
    // v_phi swirl carried on a 2D grid — its KE folds all 3 components). so the const-
    // generic `<NCOMP>` instance drives EVERY geometry; `ndim` only selects the emit grid
    // loop, exactly like rmhd_c2p_gv. numerically equivalent within ULP to the old builder.
    // CPU+GPU validated (substrate_adiabatic_sod/hydro_gpu cartesian; cylindrical_* cyl r-z).
    let (k, writes) = match geom.ncomp {
        1 => symbi_discretize::gv::adiabatic_c2p_gv::<1>(),
        2 => symbi_discretize::gv::adiabatic_c2p_gv::<2>(),
        3 => symbi_discretize::gv::adiabatic_c2p_gv::<3>(),
        nc => panic!("adiabatic_c2p_gv: unsupported ncomp {nc}"),
    };
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the SRHD (special-relativistic) cons->prim: the FIRST iterative c2p. the
// relativistic pressure is a root of a 1D equation found by a fixed-bound masked
// Newton (`operators::iterate`, `max_iters` baked at codegen); rho/vel/Lorentz
// follow algebraically. proves the substrate emits a compilable iterative kernel
// — the deep iterate lowers in linear time via the DAG-preserving lowering
// (docs/design/13), where `as_op` would have exploded. pointwise, D-generic.
fn gen_srhd_c2p(out_dir: &str, ndim: u8, max_iters: usize) {
    let name = format!("srhd_c2p_{ndim}d");
    // built from symbi-hydro's branch-free `srhd_recover` at S=Gv — the SINGLE-SOURCE
    // physics (the iterative relativistic c2p; the Newton lowers to one IterateInline).
    // srhd c2p is cartesian-only + ncomp==ndim (no cyl r-z swirl srhd), so this is the
    // ONLY srhd c2p path. numerically equivalent within ULP, NOT bit-identical to the old
    // builder (which hand-cancels rho in c2/h). max_iters bakes the fixed Newton count.
    let (k, writes) = match ndim {
        1 => symbi_discretize::gv::srhd_c2p_gv::<1>(max_iters),
        2 => symbi_discretize::gv::srhd_c2p_gv::<2>(max_iters),
        3 => symbi_discretize::gv::srhd_c2p_gv::<3>(max_iters),
        _ => panic!("srhd_c2p_gv: unsupported ndim {ndim}"),
    };
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the SRHD face flux: reconstruction + the canonical HLLE with RELATIVISTIC
// U(prim)/F(U)/wave speeds (symbi_discretize::srhd_hlle_flux). mass + momentum +
// energy (D, S_k, tau). same structure as the adiabatic flux; only the physics
// (Lorentz factor, relativistic enthalpy + sound speed + characteristic speeds)
// differs. dimension-generic; codegen instantiates the sweep-0 1D kernel here.
fn gen_srhd_face_flux(out_dir: &str, ndim: u8, dir: u8) {
    let name = format!("srhd_face_flux_{ndim}d_{dir}");
    // the gv single-source physics: PLM reconstruction (Gv stencil) composed with
    // symbi-hydro's `riemann::hlle` at the `Srhd` regime (relativistic U/F/wave speeds),
    // traced at S=Gv — replacing the `srhd_hlle_flux` Expr builder + `srhd_side`. srhd flux
    // is cartesian-only + ncomp == ndim (no cyl r-z srhd), so this is the ONLY srhd flux
    // path. numerically equivalent within ULP.
    let (k, writes) = match ndim {
        1 => symbi_discretize::gv::srhd_flux_gv::<1>(dir),
        2 => symbi_discretize::gv::srhd_flux_gv::<2>(dir),
        3 => symbi_discretize::gv::srhd_flux_gv::<3>(dir),
        _ => panic!("srhd_flux_gv: unsupported ndim {ndim}"),
    };
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the RMHD (relativistic MHD) cons->prim: the KKC false-position (a vector-state
// bracketed iterate over kkc_fmu44, with find_mu_plus + Illinois half-damp,
// `max_iters` baked). reads the 8-field conserved (D, S_k, tau, B_k) + gamma;
// writes (rho, v_k, p) — B passes through. the deep bracketed iterate lowers in
// linear time via the DAG-preserving lowering. pointwise, D-generic.
fn gen_rmhd_c2p(out_dir: &str, ndim: u8, max_iters: usize) {
    let name = format!("rmhd_c2p_{ndim}d");
    // built from symbi-hydro's branch-free `rmhd_recover` at S=Gv — the SINGLE-SOURCE
    // physics (the KKC false-position; the 6-state bracket lowers to one multi-accumulator
    // IterateInline). RMHD vectors are always 3-component, so the gv builder is grid-ndim
    // -independent; `ndim` only selects the emit grid loop. numerically equivalent within
    // ULP to the old builder. max_iters bakes the fixed false-position count.
    let (k, writes) = symbi_discretize::gv::rmhd_c2p_gv(max_iters);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the RMHD face flux: reconstruction + the canonical HLLE with the relativistic-MHD
// U(prim)/F(U) (D, S_k, tau hydro components) + the QUARTIC wave speeds
// (symbi_discretize::rmhd_hlle_flux). the B-field flux (induction/EMF) is
// constrained transport (handled separately). D-generic; sweep-0 1D here.
// the gv single-source rmhd face flux: theta-MC PLM (Gv stencil) composed with
// symbi-hydro's `riemann::hlle` at the `Rmhd` regime, traced at S=Gv — replacing the
// `rmhd_hlle_flux` Expr builder + `lower_rmhd_side`. 8 conserved fluxes (D, S_k, tau, B_k).
fn emit_rmhd_flux_gv(out_dir: &str, name: &str, ndim: u8, dir: u8) {
    let (k, writes) = symbi_discretize::gv::rmhd_flux_gv(ndim, dir, dir as usize);
    emit_gv(out_dir, name, ndim, &k, &writes);
}

fn gen_rmhd_face_flux(out_dir: &str, ndim: u8) {
    emit_rmhd_flux_gv(out_dir, &format!("rmhd_face_flux_{ndim}d"), ndim, 0);
}

// ---- HLLC variants ---- the contact-resolving 3-wave Riemann solver. iso is
// HLLE-only by physics (no contact wave). cartesian, one per (ndim, dir).
fn gen_adiabatic_hllc_face_flux(out_dir: &str, ndim: u8, dir: u8) {
    let name = format!("adiabatic_face_flux_hllc_{ndim}d_{dir}");
    let (k, writes) = match ndim {
        1 => symbi_discretize::gv::adiabatic_hllc_flux_gv::<1>(dir),
        2 => symbi_discretize::gv::adiabatic_hllc_flux_gv::<2>(dir),
        3 => symbi_discretize::gv::adiabatic_hllc_flux_gv::<3>(dir),
        _ => panic!("adiabatic_hllc_flux_gv: unsupported ndim {ndim}"),
    };
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

fn gen_srhd_hllc_face_flux(out_dir: &str, ndim: u8, dir: u8) {
    let name = format!("srhd_face_flux_hllc_{ndim}d_{dir}");
    let (k, writes) = match ndim {
        1 => symbi_discretize::gv::srhd_hllc_flux_gv::<1>(dir),
        2 => symbi_discretize::gv::srhd_hllc_flux_gv::<2>(dir),
        3 => symbi_discretize::gv::srhd_hllc_flux_gv::<3>(dir),
        _ => panic!("srhd_hllc_flux_gv: unsupported ndim {ndim}"),
    };
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

fn gen_rmhd_hllc_face_flux(out_dir: &str, ndim: u8, dir: u8) {
    // name carries `_{dir}` for every ndim (incl 1D) to match the base flux + the dispatch
    // `rmhd_face_flux_hllc_{D}d_{dir}` (substrate_rmhd.rs flux()).
    let name = format!("rmhd_face_flux_hllc_{ndim}d_{dir}");
    let (k, writes) = symbi_discretize::gv::rmhd_hllc_flux_gv(ndim, dir, dir as usize);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

fn gen_rmhd_hlld_face_flux(out_dir: &str, ndim: u8, dir: u8) {
    let name = format!("rmhd_face_flux_hlld_{ndim}d_{dir}");
    let (k, writes) = symbi_discretize::gv::rmhd_hlld_flux_gv(ndim, dir, dir as usize);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the RMHD constrained-transport curl B-update (2D in-plane, dB/dt=-curl(E) from
// the out-of-plane edge EMF Ez). integer-offset load_at stencil; preserves
// div(B)=0 to machine precision. instantiated at ndim=2.
fn gen_rmhd_ct_curl(out_dir: &str) {
    // per-component 2.5D in-plane curl (dir=0 -> bx, dir=1 -> by), each from the corner Ez.
    for dir in 0..2 {
        let (k, writes) = rmhd_ct_curl_2d_dir_gv(dir);
        emit_gv(out_dir, &format!("rmhd_ct_curl_2d_{dir}"), 2, &k, &writes);
    }
}

// the RMHD face flux along a given sweep `dir` at 3D (per-dir kernel; the
// reconstruction axis is baked). writes the 8 conserved fluxes (D,S,tau,B).
fn gen_rmhd_face_flux_3d(out_dir: &str, dir: u8) {
    emit_rmhd_flux_gv(out_dir, &format!("rmhd_face_flux_3d_{dir}"), 3, dir);
}

// the RMHD CT edge EMF along edge `dir` at 3D (per-dir kernel). writes one edge EMF.
// the corner edge-EMF: `name_k` is the out-of-plane vector component the edge carries (the
// dispatch key — 3D: name_k == dir; 2.5D cartesian: name_k=2 (E_z); cyl r-z: name_k=1 (E_phi)).
// `g1`/`g2` are the two GRID offset axes the corner stencil walks, DECOUPLED from name_k so the
// same component-agnostic kernel serves every geometry (cyl r-z routes components {0,2} onto grid
// axes {0,1}). the runtime binds vel_p1/bcell_p1/... to the in-plane components via ct_edges(axes).
fn gen_rmhd_edge_emf(out_dir: &str, name_k: u8, ndim: u8, g1: usize, g2: usize) {
    let (k, writes) = rmhd_edge_emf_gv(ndim as usize, g1, g2);
    emit_gv(out_dir, &format!("rmhd_edge_emf_{ndim}d_{name_k}"), ndim, &k, &writes);
}

// the RMHD CFL wave-speed map (3D): per-cell max over axes of the quartic
// max(|lambda_-|,|lambda_+|). host folds max + cfl_from_smax.
fn gen_rmhd_wave_speed_map(out_dir: &str, ndim: u8, geom: Geom) {
    let name = format!("rmhd_wave_speed_map{}_{ndim}d", geom.suffix());
    let (k, writes) =
        rmhd_wave_speed_map_gv(geom.coords, &geom.spacing, &geom.axes, ndim as usize);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the per-cell exact-quartic wave speeds: prim -> wave_speed_l[d]/wave_speed_r[d] for d=0..2.
// geometry-free (the quartic depends only on the state, not the metric), so a single 3D kernel.
fn gen_rmhd_wave_speeds_cell(out_dir: &str, ndim: u8) {
    let (k, writes) = rmhd_wave_speeds_cell_gv(ndim as usize);
    emit_gv(out_dir, &format!("rmhd_wave_speeds_cell_{ndim}d"), ndim, &k, &writes);
}

// ---- newtonian MHD ---- the non-relativistic ideal-MHD regime. only THREE
// regime-specific kernels: the ALGEBRAIC c2p (no iteration -> no current-sheet
// failure), the closed-form-magnetosonic HLLE face flux, and the CFL wave-speed
// map. all constrained-transport kernels (edge EMF, curl, bcell, efield, ghost)
// are SHARED with RMHD (B evolution is regime-agnostic Faraday) and are NOT
// re-emitted here — the NMHD substrate reuses the rmhd_* CT kernels.

// the NMHD c2p: `nmhd_recover` (strip 1/2|B|^2, invert hydro) at S=Gv. branch-free
// algebraic math -> a single straight-line kernel (no IterateInline, unlike RMHD's
// false-position). writes (rho, v_k, p); B passes through (CT-evolved).
fn gen_nmhd_c2p(out_dir: &str, ndim: u8) {
    let name = format!("nmhd_c2p_{ndim}d");
    let (k, writes) = symbi_discretize::gv::nmhd_c2p_gv();
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the NMHD face flux along sweep `dir` at 3D: theta-MC PLM (Gv stencil) composed with
// `riemann::hlle` at the `NewtonianMhd` regime — the Davis fan speeds are the inline
// closed-form magnetosonic (no per-cell materialization, unlike the RMHD quartic).
// writes the 8 conserved fluxes (D, S_k, nrg, B_k).
fn gen_nmhd_face_flux_3d(out_dir: &str, dir: u8) {
    let (k, writes) = symbi_discretize::gv::nmhd_flux_gv(3, dir, dir as usize);
    emit_gv(out_dir, &format!("nmhd_face_flux_3d_{dir}"), 3, &k, &writes);
}

// the NMHD HLLC / HLLD face fluxes (contact-resolving / full 5-wave) along sweep `dir`.
// the HLLD path is the robustness payoff: algebraic c2p + the closed-form 5-wave solver
// keep Orszag-Tang stable. inline wave speeds (no materialized ws_l/ws_r).
fn gen_nmhd_hllc_face_flux(out_dir: &str, dir: u8) {
    let (k, writes) = symbi_discretize::gv::nmhd_hllc_flux_gv(3, dir, dir as usize);
    emit_gv(out_dir, &format!("nmhd_face_flux_hllc_3d_{dir}"), 3, &k, &writes);
}
fn gen_nmhd_hlld_face_flux(out_dir: &str, dir: u8) {
    let (k, writes) = symbi_discretize::gv::nmhd_hlld_flux_gv(3, dir, dir as usize);
    emit_gv(out_dir, &format!("nmhd_face_flux_hlld_3d_{dir}"), 3, &k, &writes);
}

// the NMHD CFL wave-speed map (3D): per-cell max over axes of the EXACT closed-form
// magnetosonic max(|sl|,|sr|), folded with the geometry inverse-width. one per geometry.
fn gen_nmhd_wave_speed_map(out_dir: &str, ndim: u8, geom: Geom) {
    let name = format!("nmhd_wave_speed_map{}_{ndim}d", geom.suffix());
    let (k, writes) =
        nmhd_wave_speed_map_gv(geom.coords, &geom.spacing, &geom.axes, ndim as usize);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// ---- ISOTHERMAL MHD kernels (Mignone 2007) -------------------------------------
// same shapes as the NMHD emits but over the no-energy state: c2p writes (rho, v_k)
// only, the face flux writes (D, S_k, B_k) only, and the closure scalar is `cs`.
fn gen_imhd_c2p(out_dir: &str, ndim: u8) {
    let name = format!("imhd_c2p_{ndim}d");
    let (k, writes) = symbi_discretize::gv::imhd_c2p_gv();
    emit_gv(out_dir, &name, ndim, &k, &writes);
}
fn gen_imhd_face_flux_3d(out_dir: &str, dir: u8) {
    let (k, writes) = symbi_discretize::gv::imhd_flux_gv(3, dir, dir as usize);
    emit_gv(out_dir, &format!("imhd_face_flux_3d_{dir}"), 3, &k, &writes);
}
fn gen_imhd_hlld_face_flux(out_dir: &str, dir: u8) {
    let (k, writes) = symbi_discretize::gv::imhd_hlld_flux_gv(3, dir, dir as usize);
    emit_gv(out_dir, &format!("imhd_face_flux_hlld_3d_{dir}"), 3, &k, &writes);
}
fn gen_imhd_wave_speed_map(out_dir: &str, ndim: u8, geom: Geom) {
    let name = format!("imhd_wave_speed_map{}_{ndim}d", geom.suffix());
    let (k, writes) =
        symbi_discretize::gv::imhd_wave_speed_map_gv(geom.coords, &geom.spacing, &geom.axes, ndim as usize);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the RMHD cell-B flux predictor (Euler + RK2): flux-evolve the CELL B by the
// induction-flux divergence, so the magnetic-energy correction in bcell_from_bface
// reads the flux-implied B as b_old (matching the C++ godunov, whose scale_gas/
// add_gas include the magnetic component). in-place on bcell (bc_{c} read+written).
fn gen_rmhd_bcell_godunov_euler(out_dir: &str, geom: Geom, ndim: u8) {
    let name = format!("rmhd_bcell_godunov_euler{}_{ndim}d", geom.suffix());
    // ncomp = 3 (B is always a 3-vector); flux-divergence over ndim spatial directions.
    let (k, writes) = rmhd_bcell_godunov_euler_gv(geom.coords, &geom.spacing, ndim as usize, 3, &geom.axes);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

fn gen_rmhd_bcell_godunov_rk2(out_dir: &str, geom: Geom, ndim: u8) {
    let name = format!("rmhd_bcell_godunov_rk2{}_{ndim}d", geom.suffix());
    let (k, writes) = rmhd_bcell_godunov_rk2_gv(geom.coords, &geom.spacing, ndim as usize, 3, &geom.axes);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the canonical 3D interior cell-centered launch grade. structural fingerprint
// (rank + space names + placeholder extents) — runtime supplies real bounds at
// dispatch. both halves of the fused god+bcell launch declare THIS so the
// fusion algebra accepts the merge (gv-kernel-fusion phase B).
fn interior_3d_grade() -> LaunchGrade {
    use symbi_algebra::{domain, Space};
    LaunchGrade::from_domain(&domain([
        Space { name: "i", lo: 0, hi: 1 },
        Space { name: "j", lo: 0, hi: 1 },
        Space { name: "k", lo: 0, hi: 1 },
    ]))
}

// the RMHD GAS-STAGE + CELL-B-PREDICTOR fused launch. the two used to dispatch
// back-to-back inside `substrate_rmhd::god_stage`; they share grid + dt and
// write to disjoint slots (cons.{den,mom,nrg} vs bc_{0,1,2}). `try_fuse` merges
// the two GvKernels into one — the substrate then issues one launch per stage.
//
// emits `rmhd_godunov_and_bcell_{variant}{geom_suffix}_3d` for variant in
// {euler, rk2}; the GAS-stage builder args mirror `gen_godunov_stage` for the
// rmhd 3D row (ncomp=3, has_energy=true, GeoSource::Rmhd).
fn gen_mhd_godunov_and_bcell(out_dir: &str, prefix: &str, geom: Geom, variant: &str) {
    // the CT bcell predictor is regime-agnostic (Faraday induction) — always the rmhd_*
    // kernel; only the GAS stage's geometric source differs by regime (geo_source(prefix)).
    let bcell_kw = match variant {
        "euler" => rmhd_bcell_godunov_euler_gv(geom.coords, &geom.spacing, 3, 3, &geom.axes),
        "rk2" => rmhd_bcell_godunov_rk2_gv(geom.coords, &geom.spacing, 3, 3, &geom.axes),
        other => panic!("gen_mhd_godunov_and_bcell: unknown variant `{other}`"),
    };
    let (mut k_god, w_god) = symbi_discretize::gv::godunov_stage_gv_with_fused_sources(
        geom.coords, &geom.spacing, &geom.axes, 3, 3, true,
        geo_source(prefix), &[], /* mag_from_bcell = */ true, // FUSED: read cell-B via bc_k so try_fuse dedups it
    );
    let (mut k_bcell, w_bcell) = bcell_kw;
    let grade = interior_3d_grade();
    k_god.grade = grade.clone();
    k_bcell.grade = grade;

    let (fused, writes) = try_fuse(k_god, w_god, k_bcell, w_bcell)
        .unwrap_or_else(|e| panic!(
            "gen_rmhd_godunov_and_bcell {variant}: try_fuse rejected the pair: {e}\n\
             this should be a structural diagnostic — investigate the rejected hazard \
             before re-emitting the fused kernel.",
        ));

    let name = format!("{prefix}_godunov_and_bcell_{variant}{}_3d", geom.suffix());
    emit_gv(out_dir, &name, 3, &fused, &writes);
}

// the RMHD 3D constrained-transport curl B-update along ONE face axis `dir`
// (per-dir kernel; the reference rmhd_bface_update monomorphized per sweep).
// dB_dir/dt = -curl(E)_dir from the two transverse edge EMFs. in-place on b.
// PER-DIR because each efield[k] is allocated extended only on its two
// transverse axes, so a combined kernel on the union domain would read OOB.
fn gen_rmhd_ct_curl_3d_dir(out_dir: &str, dir: u8, geom: Geom) {
    let name = format!("rmhd_ct_curl_3d_{dir}{}", geom.suffix());
    // in-place on b (pointwise read; only the transverse E are stenciled). cartesian uses the
    // uniform id scalars; curvilinear (_sph) the gv orthogonal-curl scale-factor weights.
    let (k, writes) = rmhd_ct_curl_3d_dir_gv(geom.coords, &geom.spacing, dir as usize);
    emit_gv(out_dir, &name, 3, &k, &writes);
}

// the 2.5D cylindrical r-z (axisymmetric) CT curl B-update along in-plane face axis `dir`
// (0 -> B_r, 1 -> B_z), from the single out-of-plane corner EMF E_phi. dir=1 carries the
// (1/r) d_r(r E_phi) metric; dir=0 is flat. name matches the geom_suffix dispatch "_cyl_rz".
fn gen_rmhd_ct_curl_cyl_rz(out_dir: &str, dir: u8, geom: &Geom) {
    let (k, writes) = rmhd_ct_curl_cyl_rz_gv(dir as usize, &geom.spacing);
    emit_gv(out_dir, &format!("rmhd_ct_curl_2d_{dir}_cyl_rz"), 2, &k, &writes);
}

// the 2.5D cylindrical r-phi DISK CT curl B-update along in-plane face axis `dir` (0 -> B_r,
// 1 -> B_phi), from the single out-of-plane corner EMF E_z. dir=0 carries the (1/r) d_phi metric
// (mirror of r-z's dir=1); dir=1 is flat. name matches the geom_suffix dispatch "_cyl_rphi".
fn gen_rmhd_ct_curl_cyl_rphi(out_dir: &str, dir: u8, geom: &Geom) {
    let (k, writes) = rmhd_ct_curl_cyl_rphi_gv(dir as usize, &geom.spacing);
    emit_gv(out_dir, &format!("rmhd_ct_curl_2d_{dir}_cyl_rphi"), 2, &k, &writes);
}

// the RMHD lattice-map ghost fill (3D): pulls back prim rho/vel/pre + mhd.bcell at the per-axis
// source coord, with vel_sign flips on vel + B. in-place. the gv multi-axis pullback stencil.
fn gen_rmhd_ghost_fill(out_dir: &str) {
    let (k, writes) = rmhd_ghost_fill_gv(3, 3);
    emit_gv(out_dir, "rmhd_ghost_fill_3d", 3, &k, &writes);
}
fn gen_imhd_ghost_fill(out_dir: &str) {
    let (k, writes) = symbi_discretize::gv::imhd_ghost_fill_gv(3, 3);
    emit_gv(out_dir, "imhd_ghost_fill_3d", 3, &k, &writes);
}

// the RMHD CT face->cell B interpolation + magnetic-energy correction.
// ndim = number of in-plane (face-staggered) B components = grid dim D; the kernel name
// reflects the grid dim. out-of-plane components (2.5D Bz) are not interpolated here.
fn gen_rmhd_bcell_from_bface(out_dir: &str, ndim: u8) {
    let (k, writes) = rmhd_bcell_from_bface_gv(ndim as usize);
    emit_gv(out_dir, &format!("rmhd_bcell_from_bface_{ndim}d"), ndim, &k, &writes);
}
// isothermal face->cell B: interpolation only, NO 1/2|B|^2 energy correction.
fn gen_imhd_bcell_from_bface(out_dir: &str, ndim: u8) {
    let (k, writes) = symbi_discretize::gv::imhd_bcell_from_bface_gv(ndim as usize);
    emit_gv(out_dir, &format!("imhd_bcell_from_bface_{ndim}d"), ndim, &k, &writes);
}

// the RMHD RK2 edge-EMF save (e_n = e, pointwise copy; out-of-place) and time-average
// (e = 0.5*(e + e_n), in-place on e). single-field 3D gv kernels; the KernelSet calls each
// once per edge axis (save also reused for the bcell^n snapshot — a generic 2-buffer copy).
// pointwise copies, but the EMITTED kernel's index ABI is per-ndim — the device save/avg
// (efield RK2 + the bcell^n snapshot copy) must launch the `_{ndim}d` instance matching the
// field's dimensionality, else a 3d kernel on a 2d field reads a garbage 3rd stride (OOB).
fn gen_rmhd_save_efield(out_dir: &str, ndim: u8) {
    let (k, writes) = rmhd_save_efield_gv();
    emit_gv(out_dir, &format!("rmhd_save_efield_{ndim}d"), ndim, &k, &writes);
}

fn gen_rmhd_average_efield(out_dir: &str, ndim: u8) {
    let (k, writes) = rmhd_average_efield_gv();
    emit_gv(out_dir, &format!("rmhd_average_efield_{ndim}d"), ndim, &k, &writes);
}

// the SRHD CFL wave-speed map: per-cell max(|lambda_-|, |lambda_+|), the
// relativistic 1D characteristic speeds. like the iso map but the relativistic
// closed form (no inv_dx baked); the host folds max + cfl_from_smax(s_max,cfl,dx).
fn gen_srhd_wave_speed_map(out_dir: &str, ndim: u8, geom: Geom) {
    let name = format!("srhd_wave_speed_map{}_{ndim}d", geom.suffix());
    let (k, writes) =
        srhd_wave_speed_map_gv(geom.coords, &geom.spacing, &geom.axes, ndim as usize);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// the lattice-map pullback ghost fill (docs/design/11): read prim at the per-axis
// integer source coord (periodic/reflect/outflow on a runtime map_type), write at
// the cell, with vel_sign per momentum component. IN-PLACE (write path == input
// path). dimension-generic; codegen instantiates the 1D kernel here.
fn gen_iso_ghost_fill(out_dir: &str, ndim: u8, geom: Geom) {
    let name = format!("iso_ghost_fill{}_{ndim}d", geom.suffix());
    let (k, writes) = iso_ghost_fill_gv(ndim as usize, geom.ncomp as usize, &geom.axes);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// P2 (curvilinear): the SPHERICAL mass-law godunov — `rho_new = rho - dt*div(F)` with the
// analytic AREA-WEIGHTED divergence `(1/V)(F_hi*A_hi - F_lo*A_lo)` from the gv `cell_geometry_gv`.
// a host test extracts div = -rho_new (rho=0, dt=1) and bit-diffs it against the analytic
// spherical-shell formula.
fn gen_godunov_mass_sph_1d(out_dir: &str) {
    let g = Geom::sph(1);
    let (k, writes) = godunov_mass_gv(g.coords, &g.spacing, &g.axes, 1);
    emit_gv(out_dir, "godunov_mass_sph_1d", 1, &k, &writes);
}

// P3b (curvilinear): the centrifugal/coriolis INERTIAL momentum source on a 2D spherical
// grid (single theta cell -> isolates the radial centrifugal). regime-agnostic via the
// conserved momentum: a host test sets cons.mom (= rho v Newtonian, or rho h W^2 v for
// SRHD) + v_r, v_theta and checks s_0 = mom_theta*v_theta/r_c (centrifugal), s_1 =
// -mom_r*v_theta/r_c (coriolis), r_c the volume-weighted radial centroid.
fn gen_inertial_momentum_probe_sph_2d(out_dir: &str) {
    let (k, writes) = inertial_momentum_probe_gv(Coords::Spherical, &[Spacing::Uniform; 2], 2);
    emit_gv(out_dir, "inertial_momentum_sph_2d", 2, &k, &writes);
}

// P4 (curvilinear): the iso CFL wave-speed map on a LOG-spaced spherical radial grid.
// the per-cell physical inverse width 1/(h_r*dr_i) tracks the GROWING log zones
// (h_r=1, dr_i grows), so a host test (v=0) checks lambda[i] = cs/dr_i per cell — not
// the single uniform inv_dx. proves the metric-correct per-cell CFL length.
fn gen_iso_wave_speed_map_sph_log_1d(out_dir: &str) {
    let geom = Geom::sph(1).with_spacing(vec![Spacing::Log]);
    let (k, writes) = iso_wave_speed_map_gv(geom.coords, &geom.spacing, &geom.axes, 1);
    emit_gv(out_dir, "iso_wave_speed_map_sph_log_1d", 1, &k, &writes);
}

// P3b (curvilinear, RMHD): the FULL relativistic-MHD geometric momentum source on a 3D
// spherical grid via the RMHD adapter onto the regime-generic builder — TOTAL-pressure
// source + gas inertial (wgam2 v^2) + magnetic tension (-bmu^2). a host test checks the
// radial source s_0 against the analytic ptot*3(r_h^2-r_l^2)/(r_h^3-r_l^3) +
// [wgam2(vt^2+vp^2) - (bmu_t^2+bmu_p^2)]/r_c (theta symmetric about pi/2 -> cot=0).
fn gen_rmhd_geometric_source(out_dir: &str, geom: Geom) {
    // the gv full source via gv_geometric_source(Rmhd): total-pressure + gas inertial (wgam2 v^2)
    // + magnetic tension (-bmu^2), the SAME coord-generic path the rmhd curvilinear godunov uses.
    // emitted per curvilinear geometry (spherical + cylindrical) for the host cross-check; the
    // production source is fused INTO the rmhd godunov_stage, not this standalone probe.
    let (k, writes) = geometric_momentum_source_probe_gv(
        geom.coords, &geom.spacing, &geom.axes, 3, 3, GeoSource::Rmhd,
    );
    assert!(
        k.field_inputs.iter().any(|(_, rt)| rt.name() == "prim.mag[0]"),
        "RMHD source must read the magnetic field (the four-vector tension)"
    );
    let name = format!("rmhd_geometric_source{}_3d", geom.suffix());
    emit_gv(out_dir, &name, 3, &k, &writes);
}

// the geometry-algebra probe (P1, docs/design — curvilinear): write the per-cell inverse
// volume + dir-0 face areas + dir-0 volume-weighted centroid, computed FROM THE INDEX via the
// gv metric (`cell_geometry_gv`). a host test bit-diffs these against the analytic formulas
// (incl. log spacing) — so the gv geometry foundation is validated against analytic before the
// curvilinear godunov + geometric source build on it.
fn gen_geometry_probe(out_dir: &str, ndim: u8, coords: Coords, spacing: &[Spacing], name: &str) {
    let (k, writes) = geometry_probe_gv(coords, spacing, ndim as usize);
    emit_gv(out_dir, name, ndim, &k, &writes);
}

// immersed-body forward source (docs/design/19 P1/P2): the cons->cons kernel — softened
// Newtonian GRAVITY + Bondi-Hoyle mass ACCRETION from MAX_BODIES point masses. in-place
// writes cons.den (accretion removes mass) / cons.mom_* / cons.nrg; body params arrive as
// scalar params packed by the runtime (MAX_BODIES imported from symbi-ib).
fn gen_body_source(out_dir: &str, ndim: u8, coords: Coords) {
    let name = format!("body_source{}_{ndim}d", coords_suffix(coords));
    let g = Geom::identity(coords, ndim);
    let (k, writes) = body_source_gv(MAX_BODIES, coords, ndim as usize, g.ncomp as usize, &g.axes);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// immersed-body BACKWARD feedback (docs/design/19 P3): per cell, per body, the force /
// torque / accreted-mass contributions -> scratch fields a device reduction sums into
// each body's BodyDelta. reads cons (pure); writes MAX_BODIES*(ndim+4) scratch outputs.
fn gen_body_feedback(out_dir: &str, ndim: u8, coords: Coords) {
    let name = format!("body_feedback{}_{ndim}d", coords_suffix(coords));
    let g = Geom::identity(coords, ndim);
    let (k, writes) = body_feedback_gv(MAX_BODIES, coords, ndim as usize, g.ncomp as usize, &g.axes);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

// immersed-body ISOTHERMAL forward/backward: identical physics, but cs comes from
// prim.pre (= cs^2(x)*rho) and there is no energy slot. emitted as `body_source_iso`
// / `body_feedback_iso` so the iso substrate dispatches them by name.
fn gen_body_source_iso(out_dir: &str, ndim: u8, coords: Coords) {
    let name = format!("body_source_iso{}_{ndim}d", coords_suffix(coords));
    let g = Geom::identity(coords, ndim);
    let (k, writes) = body_source_iso_gv(MAX_BODIES, coords, ndim as usize, g.ncomp as usize, &g.axes);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

fn gen_body_feedback_iso(out_dir: &str, ndim: u8, coords: Coords) {
    let name = format!("body_feedback_iso{}_{ndim}d", coords_suffix(coords));
    let g = Geom::identity(coords, ndim);
    let (k, writes) = body_feedback_iso_gv(MAX_BODIES, coords, ndim as usize, g.ncomp as usize, &g.axes);
    emit_gv(out_dir, &name, ndim, &k, &writes);
}

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    gen_godunov_mass_1d(&out_dir);
    // amr field transfer (docs/design/22 phase 2): the refinement-lattice
    // pullbacks at ratio 2, every dimension.
    for ndim in 1u8..=3 {
        gen_refine_transfer(&out_dir, ndim);
    }
    gen_scalar_ghost_fill(&out_dir);
    // geometry-algebra probes: cartesian + spherical, uniform + log radial spacing.
    gen_geometry_probe(&out_dir, 1, Coords::Cartesian, &[Spacing::Uniform], "geom_cart_unif_1d");
    gen_geometry_probe(&out_dir, 1, Coords::Spherical, &[Spacing::Uniform], "geom_sph_unif_1d");
    gen_geometry_probe(&out_dir, 1, Coords::Spherical, &[Spacing::Log], "geom_sph_log_1d");
    gen_geometry_probe(
        &out_dir, 2, Coords::Spherical, &[Spacing::Log, Spacing::Uniform], "geom_sph_log_2d",
    );
    // P2: the spherical area-weighted mass-law divergence probe.
    gen_godunov_mass_sph_1d(&out_dir);
    // P3/P3b: the SPHERICAL adiabatic hydro kernels (the curvilinear instances the
    // M-generic AdiabaticSubstrateKernelSet selects on a spherical SimState) — the SAME
    // builders as Cartesian with set_geometry(Spherical): area-weighted divergence +
    // geometric pressure source (+ inertial for ndim>=2) + per-cell CFL widths. the
    // adiabatic CFL shares the iso wave-speed map.
    for ndim in 1u8..=3 {
        gen_curvilinear_hydro(&out_dir, ndim, Geom::sph(ndim));
    }
    // P3b (RMHD): the full relativistic-MHD geometric source (3D spherical) — pressure +
    // gas inertial + magnetic tension, via the RMHD adapter onto the generic builder.
    gen_rmhd_geometric_source(&out_dir, Geom::sph(3));
    gen_rmhd_geometric_source(&out_dir, Geom::cyl_3d());
    // P4: the iso CFL wave-speed map with per-cell physical widths (log-spherical).
    gen_iso_wave_speed_map_sph_log_1d(&out_dir);
    // P3b: the Newtonian inertial (centrifugal/coriolis) momentum source probe.
    gen_inertial_momentum_probe_sph_2d(&out_dir);
    // the three hydro regimes are FULLY D-GENERIC: one builder each, instantiated
    // at every dimension 1..=3 (and per sweep dir for the flux — the reconstruction
    // axis is baked per kernel instance). the D-generic SubstrateKernelSet<.., const D>
    // picks the instance by name (`kernel_by_name`). the godunov / snapshot / rk2
    // builders are EOS-generic — `has_energy` adds the energy conservation law
    // (iso = false; adiabatic + srhd = true).
    for ndim in 1u8..=3 {
        // isothermal Euler (no energy law; the EOS closure p = cs^2*rho is in c2p).
        gen_iso_c2p(&out_dir, ndim);
        gen_iso_wave_speed_map(&out_dir, ndim, Geom::cart(ndim));
        gen_iso_ghost_fill(&out_dir, ndim, Geom::cart(ndim));
        gen_godunov_stage(&out_dir, ndim, "iso", false, Geom::cart(ndim), None);
        gen_snapshot(&out_dir, ndim, "iso", false, Geom::cart(ndim));
        // adiabatic (ideal-gas Euler): the same EOS-generic update + the energy law
        // and the closed-form c2p closure (shares iso's wave-speed map + ghost fill).
        gen_adiabatic_c2p(&out_dir, ndim, Geom::cart(ndim));
        gen_godunov_stage(&out_dir, ndim, "adiabatic", true, Geom::cart(ndim), None);
        gen_snapshot(&out_dir, ndim, "adiabatic", true, Geom::cart(ndim));
        // SRHD (special-relativistic Euler): the ITERATIVE c2p (20-step masked
        // Newton, docs/design/14) + the relativistic flux/wave-speed map; the
        // godunov/snapshot are the SAME EOS-generic builders (D/S_k/tau).
        gen_srhd_c2p(&out_dir, ndim, 20);
        gen_srhd_wave_speed_map(&out_dir, ndim, Geom::cart(ndim));
        gen_godunov_stage(&out_dir, ndim, "srhd", true, Geom::cart(ndim), None);
        gen_snapshot(&out_dir, ndim, "srhd", true, Geom::cart(ndim));
        // one face flux per sweep dir (the reconstruction axis is baked).
        for dir in 0..ndim {
            gen_iso_face_flux(&out_dir, ndim, dir);
            gen_adiabatic_face_flux(&out_dir, ndim, dir, Geom::cart(ndim));
            gen_srhd_face_flux(&out_dir, ndim, dir);
            // HLLC variants — contact-resolving 3-wave solver, available on every
            // regime that has a contact wave. iso is HLLE-only by physics. cartesian
            // only for now (curvilinear HLLC = follow-up).
            gen_adiabatic_hllc_face_flux(&out_dir, ndim, dir);
            gen_srhd_hllc_face_flux(&out_dir, ndim, dir);
        }
    }
    // RMHD HLLC + HLLD — 1D + 3D variants matching the HLLE RMHD layout
    // (no 2D RMHD today). HLLD is now fully carrier-generic (see hlld.rs).
    gen_rmhd_hllc_face_flux(&out_dir, 1, 0);
    gen_rmhd_hlld_face_flux(&out_dir, 1, 0);
    for dir in 0..3u8 {
        gen_rmhd_hllc_face_flux(&out_dir, 3, dir);
        gen_rmhd_hlld_face_flux(&out_dir, 3, dir);
    }
    // **B6-iv (Phase 3 + 3b + 4c-restructure + vi) — the DRY AOT-bake matrix**.
    //
    // every fused godunov kernel symbi-aot emits is one point in the cube:
    //
    //   {regime}  ×  {fused family}  ×  {ndim}  ×  {integrator kind}  ×  {geometry}
    //
    // declaring it as data + a nested loop replaces the copy-paste fan-out.
    // adding SRHD / RMHD = one row in `REGIMES`; adding accretion = one row
    // in `FAMILIES`; adding spherical = wrap a `for geom in GEOMS` loop
    // (deferred until the curvilinear fused path validates on GPU). this
    // is the LOAD-BEARING shape: every new fused-kernel variant is a data
    // addition, never a new emit block. ONE godunov-stage kernel per cell
    // serves every SSP scheme — the integrator stage is a runtime coefficient,
    // no longer a codegen axis.
    for ndim in 1u8..=3 {
        for regime in REGIMES {
            for family in FUSED_FAMILIES {
                let specs = family.source_specs(ndim as usize, regime.has_energy);
                let refs: Vec<&symbi_hydro::source_spec::SourceSpec> = specs.iter().collect();
                // the FUSED variant — source folded into the godunov stage (one launch).
                gen_godunov_stage(
                    &out_dir, ndim, regime.prefix, regime.has_energy,
                    Geom::cart(ndim), Some((family.slug(), &refs)),
                );
                // the STANDALONE ADDITIVE variant — `cons += dt*S` as a separate per-stage pass.
                // the general source executor + the proven-equivalent decomposition of the fused
                // stage (plain godunov + this pass == fused stage; the S2 equivalence test).
                gen_source_apply(
                    &out_dir, ndim, regime.prefix, regime.has_energy,
                    Geom::cart(ndim), family.slug(), &refs,
                );
            }
            // the immersed-body source, fused (Cartesian for now; cyl/sph below).
            gen_godunov_with_body_source(
                &out_dir, ndim, regime.prefix, regime.has_energy, Geom::cart(ndim),
            );
        }
    }
    // the CYLINDRICAL r-z AXISYMMETRIC adiabatic family (docs/design/18): a 2-axis
    // (r, z) grid carrying a 3-component velocity — v_phi is the swirl on the folded
    // phi symmetry coordinate. ncomp=3, axes=[0,2], Cylindrical. the SAME EOS-generic
    // builders as the cartesian set, only the Geom differs (the inertial centrifugal
    // source + area-weighted divergence + phi-momentum advection fall out of it). the
    // `_cyl_rz` suffix (ncomp>naxes) matches the runtime geom_suffix; full kernel family
    // because DOF=3 != ndim=2 (the c2p/flux/snapshot/ghost can't reuse the cartesian ncomp).
    let cyl = Geom::cyl_rz();
    gen_adiabatic_c2p(&out_dir, 2, cyl.clone());
    gen_iso_wave_speed_map(&out_dir, 2, cyl.clone());
    gen_iso_ghost_fill(&out_dir, 2, cyl.clone());
    gen_godunov_stage(&out_dir, 2, "adiabatic", true, cyl.clone(), None);
    gen_snapshot(&out_dir, 2, "adiabatic", true, cyl.clone());
    for dir in 0..2 {
        gen_adiabatic_face_flux(&out_dir, 2, dir, cyl.clone());
    }
    // the CYLINDRICAL NATURAL (DOF == NDIM) hydro family for ALL THREE regimes (iso /
    // adiabatic / srhd), at 1D (radial), 2D (r-phi disk plane), and 3D (r,phi,z) — the
    // SAME gen_curvilinear_hydro helper that drives the spherical cells. only the
    // geometry-dependent godunov + wave-speed are "_cyl" (area-weighted divergence +
    // centrifugal/coriolis/hoop source); the c2p/flux/snapshot/ghost reuse the cartesian
    // ncomp == NDIM instances (DOF==D -> "" suffix). r-phi (2D) is the disk-evolve hydro
    // the immersed bodies ride (docs/design/19/20). the r-z AXISYMMETRIC swirl (DOF=3,
    // above) is the separate DOF-lifted family (newton only).
    gen_curvilinear_hydro(&out_dir, 1, Geom::cyl_1d());
    gen_curvilinear_hydro(&out_dir, 2, Geom::cyl_rphi());
    gen_curvilinear_hydro(&out_dir, 3, Geom::cyl_3d());
    // immersed-body forward source (gravity + accretion, docs/design/19 P1/P2/P4): the cons->cons
    // kernel, emitted per grid dimension (regime-agnostic) + the curvilinear variants (generic
    // physical-basis gravity, docs/design/19 P4). cylindrical 2D = the r-phi disk plane (natural
    // axes). 3D / spherical body emission follow once the generic transforms are wired (the
    // builder already handles them).
    for ndim in 1u8..=3 {
        gen_body_source(&out_dir, ndim, Coords::Cartesian);
    }
    // curvilinear body source (one generic builder per geometry): cyl r-phi disk plane (2D) +
    // r-phi-z (3D); spherical meridional (2D) + full (3D). the r-z axisymmetric body shares the
    // cyl 2D name with r-phi and needs a runtime axis-role to disambiguate (deferred).
    gen_body_source(&out_dir, 2, Coords::Cylindrical);
    gen_body_source(&out_dir, 3, Coords::Cylindrical);
    gen_body_source(&out_dir, 2, Coords::Spherical);
    gen_body_source(&out_dir, 3, Coords::Spherical);
    // backward feedback (force[ndim] + 3D torque + mass), per geometry, ndim >= 2.
    for &cc in &[Coords::Cartesian, Coords::Cylindrical, Coords::Spherical] {
        gen_body_feedback(&out_dir, 2, cc);
        gen_body_feedback(&out_dir, 3, cc);
    }
    // isothermal body source/feedback (no energy slot; cs from prim.pre): same grid
    // x geometry matrix, so an iso run with bodies has gravity + accretion + feedback.
    for ndim in 1u8..=3 {
        gen_body_source_iso(&out_dir, ndim, Coords::Cartesian);
    }
    gen_body_source_iso(&out_dir, 2, Coords::Cylindrical);
    gen_body_source_iso(&out_dir, 3, Coords::Cylindrical);
    gen_body_source_iso(&out_dir, 2, Coords::Spherical);
    gen_body_source_iso(&out_dir, 3, Coords::Spherical);
    for &cc in &[Coords::Cartesian, Coords::Cylindrical, Coords::Spherical] {
        gen_body_feedback_iso(&out_dir, 2, cc);
        gen_body_feedback_iso(&out_dir, 3, cc);
    }
    // RMHD (relativistic MHD): the KKC false-position c2p (100-step bracket), the
    // quartic-wave-speed HLLE flux, and the constrained-transport curl B-update.
    // the deepest substrate regime — iterative c2p + transcendental quartic + a
    // staggered offset stencil — all reaching build-time-compiled CPU + CUDA.
    gen_rmhd_c2p(&out_dir, 1, 100);
    gen_rmhd_c2p(&out_dir, 3, 100); // 3D for the production RmhdSubstrateKernelSet3D
    gen_rmhd_face_flux(&out_dir, 1);
    gen_rmhd_ct_curl(&out_dir);
    // 3D pieces for the production KernelSet3D: per-dir flux + edge EMF, the CT
    // single-kernels, the EOS-generic godunov/snapshot/rk2 (hydro D/S/tau).
    for dir in 0..3 {
        gen_rmhd_face_flux_3d(&out_dir, dir);
        gen_rmhd_edge_emf(&out_dir, dir, 3, ((dir + 1) % 3) as usize, ((dir + 2) % 3) as usize);
    }
    gen_rmhd_wave_speed_map(&out_dir, 3, Geom::cart(3));
    gen_rmhd_wave_speed_map(&out_dir, 3, Geom::sph(3));
    gen_rmhd_wave_speed_map(&out_dir, 3, Geom::cyl_3d());
    gen_rmhd_wave_speeds_cell(&out_dir, 3); // per-cell exact quartic -> wave_speed_l/r (geom-free)
    for dir in 0..3 {
        gen_rmhd_ct_curl_3d_dir(&out_dir, dir, Geom::cart(3));
        gen_rmhd_ct_curl_3d_dir(&out_dir, dir, Geom::sph(3));
        gen_rmhd_ct_curl_3d_dir(&out_dir, dir, Geom::cyl_3d());
    }
    gen_rmhd_bcell_from_bface(&out_dir, 3);
    gen_rmhd_bcell_godunov_euler(&out_dir, Geom::cart(3), 3);
    gen_rmhd_bcell_godunov_euler(&out_dir, Geom::sph(3), 3);
    gen_rmhd_bcell_godunov_euler(&out_dir, Geom::cyl_3d(), 3);
    gen_rmhd_bcell_godunov_rk2(&out_dir, Geom::cart(3), 3);
    gen_rmhd_bcell_godunov_rk2(&out_dir, Geom::sph(3), 3);
    gen_rmhd_bcell_godunov_rk2(&out_dir, Geom::cyl_3d(), 3);
    gen_rmhd_save_efield(&out_dir, 3);
    gen_rmhd_average_efield(&out_dir, 3);
    gen_rmhd_ghost_fill(&out_dir);
    // RMHD GAS update (D/S_k/tau) is EOS-generic — it uses the SAME unified runtime-coefficient
    // `_stage` kernel as hydro. only the constrained-transport BCELL predictor-corrector
    // (`rmhd_bcell_godunov_euler/rk2`, emitted above) + the post_godunov EMF time-average stay
    // baked + 2-stage, so the RMHD `godunov_stage` gates (a0,ac) -> {euler, rk2} on the bcell
    // step and rejects other coefficients (SSP-RK3 + CT is unimplemented).
    gen_godunov_stage(&out_dir, 3, "rmhd", true, Geom::cart(3), None);
    gen_godunov_stage(&out_dir, 3, "rmhd", true, Geom::sph(3), None);
    gen_godunov_stage(&out_dir, 3, "rmhd", true, Geom::cyl_3d(), None);
    // FUSED gas-stage + cell-B-predictor variants for all 3 geometries. one
    // launch per stage in the substrate's god_stage (vs the two-launch
    // baseline). algebra-validated: write sets disjoint (cons.* vs bc_*),
    // no inter-dependency, same 3D interior grade.
    for geom in [Geom::cart(3), Geom::sph(3), Geom::cyl_3d()] {
        gen_mhd_godunov_and_bcell(&out_dir, "rmhd", geom.clone(), "euler");
        gen_mhd_godunov_and_bcell(&out_dir, "rmhd", geom, "rk2");
    }
    gen_snapshot(&out_dir, 3, "rmhd", true, Geom::cart(3));
    // Isothermal MHD (Mignone 2007): the no-energy regime. c2p (rho, v_k only) + HLLE/HLLD
    // flux (D, S_k, B_k) + CFL map mirror NMHD; the CT stack is shared (Faraday induction is
    // regime-agnostic). gas stage carries no energy (has_energy=false).
    gen_imhd_c2p(&out_dir, 3);
    for dir in 0..3 {
        gen_imhd_face_flux_3d(&out_dir, dir);
        gen_imhd_hlld_face_flux(&out_dir, dir);
    }
    // iso CFL map + gas stage (no energy) for all 3 coords. the gas stage carries the ISOTHERMAL
    // geometric momentum source (cs^2*rho + 1/2|B|^2 pressure + inertial + lab-frame-B tension,
    // GeoSource::IsothermalMhd; Cartesian has zero source). the CT bcell predictor + edge-EMF /
    // curl / efield / ghost are regime-agnostic (reused from rmhd_*). snapshot/bcell/ghost are
    // geometry-independent (Cartesian emit covers all coords).
    for geom in [Geom::cart(3), Geom::sph(3), Geom::cyl_3d()] {
        gen_imhd_wave_speed_map(&out_dir, 3, geom.clone());
        gen_godunov_stage(&out_dir, 3, "imhd", false, geom, None);
    }
    gen_snapshot(&out_dir, 3, "imhd", false, Geom::cart(3));
    gen_imhd_bcell_from_bface(&out_dir, 3);
    gen_imhd_ghost_fill(&out_dir);
    // Newtonian MHD: the algebraic c2p + closed-form-magnetosonic HLLE flux + CFL map.
    // the constrained-transport stack (edge EMF / curl / bcell / efield / ghost) is
    // SHARED with RMHD (B evolution is regime-agnostic Faraday), so only these three
    // regime-specific physics kernels are emitted; the substrate reuses the rmhd_* CT.
    gen_nmhd_c2p(&out_dir, 3);
    for dir in 0..3 {
        gen_nmhd_face_flux_3d(&out_dir, dir);
        gen_nmhd_hllc_face_flux(&out_dir, dir);
        gen_nmhd_hlld_face_flux(&out_dir, dir);
    }
    gen_nmhd_wave_speed_map(&out_dir, 3, Geom::cart(3));
    gen_nmhd_wave_speed_map(&out_dir, 3, Geom::sph(3));
    gen_nmhd_wave_speed_map(&out_dir, 3, Geom::cyl_3d());
    // the NMHD gas stage carries the NEWTONIAN geometric momentum source (pressure +
    // inertial + magnetic tension via lab-frame B, GeoSource::NewtonianMhd) — the only
    // godunov piece that differs from RMHD by geometry. emitted for all 3 coords (Cartesian
    // has zero source, so it matches the EOS-generic stage). the fused god+bcell mirrors RMHD.
    for geom in [Geom::cart(3), Geom::sph(3), Geom::cyl_3d()] {
        gen_godunov_stage(&out_dir, 3, "nmhd", true, geom.clone(), None);
        gen_mhd_godunov_and_bcell(&out_dir, "nmhd", geom.clone(), "euler");
        gen_mhd_godunov_and_bcell(&out_dir, "nmhd", geom, "rk2");
    }
    // =========================================================================
    // 2.5D MHD (spatial D=2, vector DOF=3) constrained transport — docs/design/30.
    // cartesian. the out-of-plane Bz rides the ordinary induction-flux divergence
    // (no CT: with d/dz=0 only the in-plane field is div-B-constrained); only the
    // in-plane Bx,By use CT via the SINGLE corner E_z (edge dir=2 -> p1=x, p2=y).
    // fusion is disabled at D=2 (CPU unfused path), so no godunov_and_bcell_2d; the
    // RK2 efield save/average use the dimension-agnostic fused memcpy (no _2d copy
    // kernel needed on CPU). ncomp = 3 (B/momentum are 3-vectors) on the 2-axis grid.
    // =========================================================================
    {
        // gas/snapshot geom: cartesian, 2 grid axes, 3 vector components (DOF=3).
        let g2 = Geom::make(Coords::Cartesian, 3, vec![0, 1]);
        // shared regime-agnostic CT pieces: the corner E_z (edge dir=2), the in-plane
        // curl B-update (rmhd_ct_curl_2d already emitted above), the cell-B predictor
        // (euler/rk2, evolves all 3 components; Bz is final, Bx/By predictor), the
        // face->cell interpolation over the 2 in-plane components, and the ghosts.
        gen_rmhd_edge_emf(&out_dir, 2, 2, 0, 1);
        // device RK2 efield save/avg + the bcell^n snapshot copy on a 2D field need the 2d
        // index ABI (the 3d copy kernel OOBs on a 2d field — CUDA_ERROR_LAUNCH_FAILED).
        gen_rmhd_save_efield(&out_dir, 2);
        gen_rmhd_average_efield(&out_dir, 2);
        gen_rmhd_bcell_godunov_euler(&out_dir, g2.clone(), 2);
        gen_rmhd_bcell_godunov_rk2(&out_dir, g2.clone(), 2);
        gen_rmhd_bcell_from_bface(&out_dir, 2);
        gen_imhd_bcell_from_bface(&out_dir, 2);
        {
            let (k, w) = rmhd_ghost_fill_gv(2, 3);
            emit_gv(&out_dir, "rmhd_ghost_fill_2d", 2, &k, &w);
            let (k, w) = symbi_discretize::gv::imhd_ghost_fill_gv(2, 3);
            emit_gv(&out_dir, "imhd_ghost_fill_2d", 2, &k, &w);
            let (k, w) = symbi_discretize::scalar_ghost_fill_gv(2);
            emit_gv(&out_dir, "scalar_ghost_fill_2d", 2, &k, &w);
        }
        // RMHD regime physics (quartic HLLE flux + KKC c2p + exact-quartic CFL map +
        // the per-cell materialized wave speeds the HLLE flux reads).
        gen_rmhd_c2p(&out_dir, 2, 100);
        for dir in 0..2 {
            emit_rmhd_flux_gv(&out_dir, &format!("rmhd_face_flux_2d_{dir}"), 2, dir);
            // HLLC / HLLD 2.5D RMHD fluxes (cartesian, coord_n == dir) — parity with the 1D + 3D
            // emission so `--solver hllc|hlld` works on a 2D RMHD sim (e.g. rmhd_orszag_tang).
            gen_rmhd_hllc_face_flux(&out_dir, 2, dir);
            gen_rmhd_hlld_face_flux(&out_dir, 2, dir);
        }
        gen_rmhd_wave_speeds_cell(&out_dir, 2);
        gen_rmhd_wave_speed_map(&out_dir, 2, g2.clone());
        gen_godunov_stage(&out_dir, 2, "rmhd", true, g2.clone(), None);
        gen_snapshot(&out_dir, 2, "rmhd", true, g2.clone());
        // NMHD regime physics (algebraic c2p + closed-form magnetosonic HLLE/HLLC/HLLD).
        gen_nmhd_c2p(&out_dir, 2);
        for dir in 0..2 {
            let (k, w) = symbi_discretize::gv::nmhd_flux_gv(2, dir, dir as usize);
            emit_gv(&out_dir, &format!("nmhd_face_flux_2d_{dir}"), 2, &k, &w);
            let (k, w) = symbi_discretize::gv::nmhd_hllc_flux_gv(2, dir, dir as usize);
            emit_gv(&out_dir, &format!("nmhd_face_flux_hllc_2d_{dir}"), 2, &k, &w);
            let (k, w) = symbi_discretize::gv::nmhd_hlld_flux_gv(2, dir, dir as usize);
            emit_gv(&out_dir, &format!("nmhd_face_flux_hlld_2d_{dir}"), 2, &k, &w);
        }
        gen_nmhd_wave_speed_map(&out_dir, 2, g2.clone());
        gen_godunov_stage(&out_dir, 2, "nmhd", true, g2.clone(), None);
        gen_snapshot(&out_dir, 2, "nmhd", true, g2.clone());
        // IMHD regime physics (no-energy c2p + HLLE/HLLD flux).
        gen_imhd_c2p(&out_dir, 2);
        for dir in 0..2 {
            let (k, w) = symbi_discretize::gv::imhd_flux_gv(2, dir, dir as usize);
            emit_gv(&out_dir, &format!("imhd_face_flux_2d_{dir}"), 2, &k, &w);
            let (k, w) = symbi_discretize::gv::imhd_hlld_flux_gv(2, dir, dir as usize);
            emit_gv(&out_dir, &format!("imhd_face_flux_hlld_2d_{dir}"), 2, &k, &w);
        }
        gen_imhd_wave_speed_map(&out_dir, 2, g2.clone());
        gen_godunov_stage(&out_dir, 2, "imhd", false, g2.clone(), None);
        gen_snapshot(&out_dir, 2, "imhd", false, g2);
    }

    // =========================================================================
    // 2.5D CYLINDRICAL r-z AXISYMMETRIC MHD (docs/design/30): a 2-axis (r,z) grid carrying
    // a 3-component B/velocity — the swirl B_phi/v_phi is the out-of-plane DOF on the folded
    // phi symmetry. axes=[0,2]: grid axis 0=r (coord 0), grid axis 1=z (coord 2); phi (coord 1)
    // is out of plane. the SINGLE CT edge is E_phi (name_k=1); the in-plane curl carries the
    // cylindrical metric -(1/r) d_r(r E_phi) on the z-face (dir=1), flat on the r-face (dir=0).
    // ONLY the geometry-dependent kernels are emitted here — c2p / snapshot / ghost /
    // bcell_from_bface / save+avg-efield / wave_speeds_cell are geometry-FREE and REUSED from
    // the cartesian 2.5D block above (DOF=3 already, same field shapes). all three regimes.
    // =========================================================================
    {
        let cyl = Geom::cyl_rz(); // Cylindrical, ncomp=3, axes=[0,2] -> suffix "_cyl_rz"
        // shared regime-agnostic CT: the corner E_phi (name_k=1, grid offset axes 0,1) + the
        // metric in-plane curl + the cell-B flux predictor (area-weighted divergence, axes=[0,2]).
        gen_rmhd_edge_emf(&out_dir, 1, 2, 0, 1);
        for dir in 0..2 {
            gen_rmhd_ct_curl_cyl_rz(&out_dir, dir, &cyl);
        }
        gen_rmhd_bcell_godunov_euler(&out_dir, cyl.clone(), 2);
        gen_rmhd_bcell_godunov_rk2(&out_dir, cyl.clone(), 2);
        // RMHD regime physics: HLLE quartic flux (normal coord_n = axes[dir]) + CFL map +
        // gas godunov (cyl geo source). c2p / wave_speeds_cell / snapshot reused from above.
        gen_rmhd_wave_speed_map(&out_dir, 2, cyl.clone());
        gen_godunov_stage(&out_dir, 2, "rmhd", true, cyl.clone(), None);
        for dir in 0u8..2 {
            let cn = cyl.axes[dir as usize];
            let (k, w) = symbi_discretize::gv::rmhd_flux_gv(2, dir, cn);
            emit_gv(&out_dir, &format!("rmhd_face_flux_cyl_rz_2d_{dir}"), 2, &k, &w);
            // HLLC / HLLD parity (normal coord_n = axes[dir]) so `--solver hllc|hlld` works on a
            // cyl r-z RMHD sim (r-phi reuses the cartesian flux via the "" suffix; cart done above).
            let (k, w) = symbi_discretize::gv::rmhd_hllc_flux_gv(2, dir, cn);
            emit_gv(&out_dir, &format!("rmhd_face_flux_cyl_rz_hllc_2d_{dir}"), 2, &k, &w);
            let (k, w) = symbi_discretize::gv::rmhd_hlld_flux_gv(2, dir, cn);
            emit_gv(&out_dir, &format!("rmhd_face_flux_cyl_rz_hlld_2d_{dir}"), 2, &k, &w);
        }
        // NMHD regime physics (algebraic c2p + closed-form magnetosonic HLLE/HLLC/HLLD).
        gen_nmhd_wave_speed_map(&out_dir, 2, cyl.clone());
        gen_godunov_stage(&out_dir, 2, "nmhd", true, cyl.clone(), None);
        for dir in 0u8..2 {
            let cn = cyl.axes[dir as usize];
            let (k, w) = symbi_discretize::gv::nmhd_flux_gv(2, dir, cn);
            emit_gv(&out_dir, &format!("nmhd_face_flux_cyl_rz_2d_{dir}"), 2, &k, &w);
            let (k, w) = symbi_discretize::gv::nmhd_hllc_flux_gv(2, dir, cn);
            emit_gv(&out_dir, &format!("nmhd_face_flux_cyl_rz_hllc_2d_{dir}"), 2, &k, &w);
            let (k, w) = symbi_discretize::gv::nmhd_hlld_flux_gv(2, dir, cn);
            emit_gv(&out_dir, &format!("nmhd_face_flux_cyl_rz_hlld_2d_{dir}"), 2, &k, &w);
        }
        // IMHD regime physics (no-energy c2p + HLLE/HLLD flux).
        gen_imhd_wave_speed_map(&out_dir, 2, cyl.clone());
        gen_godunov_stage(&out_dir, 2, "imhd", false, cyl.clone(), None);
        for dir in 0u8..2 {
            let cn = cyl.axes[dir as usize];
            let (k, w) = symbi_discretize::gv::imhd_flux_gv(2, dir, cn);
            emit_gv(&out_dir, &format!("imhd_face_flux_cyl_rz_2d_{dir}"), 2, &k, &w);
            let (k, w) = symbi_discretize::gv::imhd_hlld_flux_gv(2, dir, cn);
            emit_gv(&out_dir, &format!("imhd_face_flux_cyl_rz_hlld_2d_{dir}"), 2, &k, &w);
        }
    }

    // =========================================================================
    // 2.5D CYLINDRICAL r-phi DISK MHD (docs/design/30): a 2-axis (r,phi) grid carrying a
    // 3-component B/velocity — the VERTICAL B_z/v_z is the out-of-plane DOF. axes=[0,1]: grid
    // axis 0=r (coord 0), grid axis 1=phi (coord 1); z (coord 2) is out of plane. the SINGLE CT
    // edge is E_z (name_k=2); the in-plane curl carries the cylindrical metric -(1/r) d_phi E_z
    // on the r-face (dir=0), flat on the phi-face (dir=1) — the MIRROR of r-z. the out-of-plane
    // B_z flux-evolves through the area-weighted cyl divergence (which IS the correct z-curl here,
    // unlike r-z's B_phi). the FLUX + edge-EMF are REUSED from the cartesian 2.5D block (axes [0,1]
    // = identity, so coord_n == dir and the E_z corner is bit-identical); only the metric curl,
    // wave-speed map, gas godunov (cyl geo source), and bcell predictor are geometry-dependent.
    // all three regimes.
    // =========================================================================
    {
        let cyl = Geom::cyl_rphi_mhd(); // Cylindrical, ncomp=3, axes=[0,1] -> suffix "_cyl_rphi"
        // CT: corner E_z (rmhd_edge_emf_2d_2) REUSED from the cartesian block. metric in-plane
        // curl (dir=0 B_r: (1/r)d_phi; dir=1 B_phi: flat) + the cell-B flux predictor (area-
        // weighted divergence over axes=[0,1] — correct for the out-of-plane B_z).
        for dir in 0..2 {
            gen_rmhd_ct_curl_cyl_rphi(&out_dir, dir, &cyl);
        }
        gen_rmhd_bcell_godunov_euler(&out_dir, cyl.clone(), 2);
        gen_rmhd_bcell_godunov_rk2(&out_dir, cyl.clone(), 2);
        // the FLUX is REUSED from cartesian (axes [0,1] = identity -> coord_n == dir -> bit-
        // identical; mhd_flux_suffix returns "" for r-phi). c2p / wave_speeds_cell / snapshot /
        // ghost / bcell_from_bface / save+avg-efield also reused. only wave-speed + gas godunov
        // (the cyl metric: CFL phi-width = r*dphi, centrifugal/hoop source) are emitted here.
        gen_rmhd_wave_speed_map(&out_dir, 2, cyl.clone());
        gen_godunov_stage(&out_dir, 2, "rmhd", true, cyl.clone(), None);
        gen_nmhd_wave_speed_map(&out_dir, 2, cyl.clone());
        gen_godunov_stage(&out_dir, 2, "nmhd", true, cyl.clone(), None);
        gen_imhd_wave_speed_map(&out_dir, 2, cyl.clone());
        gen_godunov_stage(&out_dir, 2, "imhd", false, cyl.clone(), None);
    }

    // =========================================================================
    // 1.5D MHD (spatial D=1, vector DOF=3) — docs/design/30. NO constrained transport:
    // C(1,2)=0 edges (the StaggerComplex empty case), so no edge_emf / ct_curl. the
    // in-plane Bx (c=0) is carried on its (thin) face but never curled -> it stays at its
    // constant IC (the "Bx is a parameter" rule, realized as the no-edge case). By,Bz
    // (c>=1, out-of-plane) ride the ordinary induction-flux divergence (bcell_godunov).
    // bcell_from_bface_1d interpolates the const Bx + the 1-component energy correction.
    // ncomp = 3 on the 1-axis grid. (rmhd_c2p_1d is already emitted above.)
    // =========================================================================
    {
        let g1 = Geom::make(Coords::Cartesian, 3, vec![0]);
        // the device bcell^n snapshot copy on a 1D field needs the 1d save kernel (no efield
        // save/avg in 1.5D — 0 edges — but the snapshot path still copies bcell on device).
        gen_rmhd_save_efield(&out_dir, 1);
        gen_rmhd_bcell_godunov_euler(&out_dir, g1.clone(), 1);
        gen_rmhd_bcell_godunov_rk2(&out_dir, g1.clone(), 1);
        gen_rmhd_bcell_from_bface(&out_dir, 1);
        gen_imhd_bcell_from_bface(&out_dir, 1);
        {
            let (k, w) = rmhd_ghost_fill_gv(1, 3);
            emit_gv(&out_dir, "rmhd_ghost_fill_1d", 1, &k, &w);
            let (k, w) = symbi_discretize::gv::imhd_ghost_fill_gv(1, 3);
            emit_gv(&out_dir, "imhd_ghost_fill_1d", 1, &k, &w);
            let (k, w) = symbi_discretize::scalar_ghost_fill_gv(1);
            emit_gv(&out_dir, "scalar_ghost_fill_1d", 1, &k, &w);
        }
        // RMHD regime physics (c2p already emitted; HLLE flux reads the materialized speeds).
        emit_rmhd_flux_gv(&out_dir, "rmhd_face_flux_1d_0", 1, 0);
        gen_rmhd_wave_speeds_cell(&out_dir, 1);
        gen_rmhd_wave_speed_map(&out_dir, 1, g1.clone());
        gen_godunov_stage(&out_dir, 1, "rmhd", true, g1.clone(), None);
        gen_snapshot(&out_dir, 1, "rmhd", true, g1.clone());
        // NMHD regime physics.
        gen_nmhd_c2p(&out_dir, 1);
        {
            let (k, w) = symbi_discretize::gv::nmhd_flux_gv(1, 0, 0);
            emit_gv(&out_dir, "nmhd_face_flux_1d_0", 1, &k, &w);
            let (k, w) = symbi_discretize::gv::nmhd_hllc_flux_gv(1, 0, 0);
            emit_gv(&out_dir, "nmhd_face_flux_hllc_1d_0", 1, &k, &w);
            let (k, w) = symbi_discretize::gv::nmhd_hlld_flux_gv(1, 0, 0);
            emit_gv(&out_dir, "nmhd_face_flux_hlld_1d_0", 1, &k, &w);
        }
        gen_nmhd_wave_speed_map(&out_dir, 1, g1.clone());
        gen_godunov_stage(&out_dir, 1, "nmhd", true, g1.clone(), None);
        gen_snapshot(&out_dir, 1, "nmhd", true, g1.clone());
        // IMHD regime physics.
        gen_imhd_c2p(&out_dir, 1);
        {
            let (k, w) = symbi_discretize::gv::imhd_flux_gv(1, 0, 0);
            emit_gv(&out_dir, "imhd_face_flux_1d_0", 1, &k, &w);
            let (k, w) = symbi_discretize::gv::imhd_hlld_flux_gv(1, 0, 0);
            emit_gv(&out_dir, "imhd_face_flux_hlld_1d_0", 1, &k, &w);
        }
        gen_imhd_wave_speed_map(&out_dir, 1, g1.clone());
        gen_godunov_stage(&out_dir, 1, "imhd", false, g1.clone(), None);
        gen_snapshot(&out_dir, 1, "imhd", false, g1);
    }

    // emit the single registry from everything generated above — replaces the
    // hand-maintained include!/const lines in lib.rs (docs/design/15 §3).
    write_registry(&out_dir);
    // STALENESS FIX: the emitted kernels are a pure function of the SUBSTRATE physics
    // (symbi-hydro carrier fns + symbi-discretize gv builders + symbi-ir emitter), none
    // of which live in THIS package. a build script with NO `rerun-if` directive reruns
    // only when this package's OWN files change (Cargo book) — NOT when a build-DEPENDENCY
    // recompiles, contrary to the prior comment here. that left the generated CPU+CUDA
    // kernels stale after any gv-builder / physics edit (GPU-vs-CPU mismatch / gpu=0 until
    // a manual `cargo clean -p symbi-aot`). watch the substrate source explicitly so any
    // physics change regenerates the kernels. NOTE: emitting any rerun-if-changed disables
    // the default whole-package watch, so build.rs is listed too.
    println!("cargo:rerun-if-changed=build.rs");
    // Gate 3 GPU smem tiling opt-in (docs/design/22). same A/B-honesty reason.
    println!("cargo:rerun-if-env-changed=SYMBI_GPU_SMEM");
    // part-1 loop-lowering: bounds-check-free field access (the ~8x spike win).
    println!("cargo:rerun-if-env-changed=SYMBI_UNCHECKED_LOADS");
    // debug-emit-knobs gates the three a/b env knobs; only track them for rebuild when the feature is on. off (default) = these envs are never read, so no need to invalidate on change.
    if std::env::var_os("CARGO_FEATURE_DEBUG_EMIT_KNOBS").is_some() {
        println!("cargo:rerun-if-env-changed=SYMBI_TILE_CPU");
        println!("cargo:rerun-if-env-changed=SYMBI_VEC_LOOP");
        println!("cargo:rerun-if-env-changed=SYMBI_GEN_SERIAL");
    }
    for dep_src in [
        "../symbi-ir/src",
        "../symbi-discretize/src",
        "../symbi-hydro/src",
        "../symbi-geometry/src",
        "../symbi-grid/src",
        "../symbi-algebra/src",
    ] {
        println!("cargo:rerun-if-changed={dep_src}");
    }
}
