[package]
name = "symbi-hydro"
version = "0.1.0"
edition = "2024"

[dependencies]
symbi-algebra = { path = "../symbi-algebra" }
symbi-carrier = { path = "../symbi-carrier" }
symbi-geometry = { path = "../symbi-geometry" }

[dev-dependencies]
symbi-ir = { path = "../symbi-ir" }
hdf5-metno = { version = "0.12", features = ["static"] }

[lints]
workspace = true
