// =============================================================================
// build_config.hpp
//
// compile-time build configuration from meson.
// types, feature flags, and derived constants based on build options.
//
// configuration sources:
//   - build_options.hpp (generated by meson from build_options.hpp.in)
//   - compile-time computation (epsilon, etc)
//
// usage:
//   using simbi::real;  // float or double based on build
//   if constexpr (build_config::column_major) { /* ... */ }
//   constexpr auto eps = build_config::epsilon;
//
// note: these are all compile-time constants. for runtime configuration
//       (environment variables, etc), see runtime_config.hpp
// =============================================================================

#ifndef SIMBI_BUILD_CONFIG_HPP
#define SIMBI_BUILD_CONFIG_HPP

#include "build_options.hpp"

#include <type_traits>

namespace simbi::build_config {

    // =========================================================================
    // floating point precision
    // =========================================================================

#if FLOAT_PRECISION
    using real = float;
#else
    using real = double;
#endif

    // derived numerical constant
    inline constexpr real epsilon = std::is_same_v<real, float> ? 1e-6f : 1e-12;

    // =========================================================================
    // memory layout
    // =========================================================================

#if COLUMN_MAJOR
    inline constexpr bool column_major = true;
#else
    inline constexpr bool column_major = false;
#endif

    inline constexpr bool row_major = !column_major;

    // =========================================================================
    // physics configuration
    // =========================================================================

#if FOUR_VELOCITY
    inline constexpr bool four_velocity = true;
#else
    inline constexpr bool four_velocity = false;
#endif

    inline constexpr bool use_beta = !four_velocity;

    // =========================================================================
    // memory management
    // =========================================================================

#if UNIFIED_MEMORY
    inline constexpr bool unified_memory = true;
#else
    inline constexpr bool unified_memory = false;
#endif

} // namespace simbi::build_config

namespace simbi {
    // top-level type alias for convenience
    using real = build_config::real;
} // namespace simbi

#endif
