# Include core sources and headers
sources = files(
  'bindings/config_converter.cpp',
  'bindings/driver.cpp',
  'bindings/evolver.cpp',
  'context/progress.cpp',
  # 'functional/monad/serializer.cpp',
  'io/console/statistics.cpp',
  'io/exceptions.cpp',
  'io/tabulate/table.cpp',
  'math/evaluator.cpp',
  'math/exp_load.cpp',
  'math/linearize.cpp',
  'physics/em/contact.cpp',
  'physics/ib/factory.cpp',
  'utility/helpers.cpp',
)
