# Include core sources and headers
sources = files(
  'bindings/config_converter.cpp',
  'bindings/driver.cpp',
  'bindings/evolver.cpp',
  'context/progress.cpp',
  'dag/evaluator.cpp',
  'dag/exp_load.cpp',
  'dag/linearize.cpp',
  'hesi/backend/event.cpp',
  'hesi/backend/memory.cpp',
  'hesi/backend/stream.cpp',
  'hesi/backend/transfer.cpp',
  'hesi/cpu/event.cpp',
  'hesi/cpu/memory.cpp',
  'hesi/cpu/stream.cpp',
  'hesi/cpu/transfer.cpp',
  'io/console/statistics.cpp',
  'io/exceptions.cpp',
  'io/tabulate/table.cpp',
  'physics/em/contact.cpp',
  'physics/em/zero.cpp',
  'physics/ib/factory.cpp',
  'utility/helpers.cpp',
)
